gravitee-io/gravitee-management-rest-api

gravitee-management-api-model/src/main/java/io/gravitee/management/model/EventEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/EventType.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewEventEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/ApiEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/EventService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/EventAlreadyExistsException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/EventNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EventServiceImpl.java
Unable to manually deploy API via Events.
=> Features/event : Manually deploy API to the Gateway

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/EventEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewEventEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/EventService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EventServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/EventServiceTest.java
Add properties to event model.
Useful to search events by api_id to get history deployments.
Useful to remove api events.
=> Enhance event with properties

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/bin/gravitee.bat
=> Windows startup script required #25

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiEventsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, pom.xml
Add api events page with events list, events diff and api rollback features
=> API history

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiEventsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> Stopping an API must create an UNPUBLISH_API event

README.adoc, src/doc/management-api-api.adoc, src/doc/management-api-application.adoc, src/doc/management-api-overview.adoc, src/doc/management-api-policy.adoc, src/doc/management-api-user.adoc
=> feat(doc): move documentation to asccidoc

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/DeploymentRequired.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/RequiredDeployment.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/processor/ApiSynchronizationProcessor.java
This closes #20, closes gravitee-io/gravitee-repository#7 and closes gravitee-io/gravitee-repository-mongodb#8
=> API Deployment is not required for all API changes

gravitee-management-api-model/src/main/java/io/gravitee/management/model/EventType.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiEventsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/EventTypeListParam.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/ApiResourceTest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiServiceTest.java, pom.xml
=> Start / stopping an API must not deploy the current definition

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PoliciesResource.java
=> fix(policies): Sort policies by name

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/provider/BadRequestExceptionMapper.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java
=> API publisher must not being able to start / stop an API already started / stopped

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/basic/BasicSecurityConfigurerAdapter.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> Role access : set API_CONSUMER and API_PUBLISHER roles

gravitee-management-api-model/pom.xml, gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/ServicesEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/analytics/HealthAnalytics.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/jackson/ServiceKeyDeserializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, pom.xml
=> feat(health-check): Health-check is considered as a reactable service

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApiContextPathAlreadyExistsException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiServiceTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/logback.xml
=> Avoid to create an API with an existing context path

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UserResource.java
This closes https://github.com/gravitee-io/issues/issues/80
=> Force logout of an unknown user (because of reset of DB or removal of user)

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiServiceTest.java
This closes https://github.com/gravitee-io/issues/issues/84
=> Check on multi subcontexts if exists

pom.xml
=> feat(healthcheck): Upgrade gravitee-definition for default expectation

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/enhancer/ApplicationEnhancer.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApplicationService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PermissionServiceImpl.java
=> fix(admin): Admin user must be able to manage all APIs and applications

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(config): allow envvar to configure gravitee.yml

README.adoc, gravitee-management-api-standalone/gravitee-management-api-standalone-container/pom.xml, gravitee-management-api-war/pom.xml, pom.xml
=> feat(dev): Make it easier to develop using Maven

gravitee-management-api-model/src/main/java/io/gravitee/management/model/analytics/Analytics.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/analytics/HealthAnalytics.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/analytics/HitsAnalytics.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/analytics/TopHitsAnalytics.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/AnalyticsRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiAnalyticsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/AnalyticsAggTypeParam.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/AnalyticsParam.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/AnalyticsService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java, pom.xml
This closes gravitee-io/issues#61
=>  feat(analytics) : add global and top hits services 

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewApiEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/ApisResourceTest.java, gravitee-management-api-service/pom.xml, gravitee-management-api-service/src/main/java/io/gravitee/management/service/SwaggerService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiServiceTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerServiceTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/swagger-petstore.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/swagger-petstore.yaml
=> feat(api): Create an API from a Swagger descriptor

gravitee-management-api-rest/pom.xml, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-service/pom.xml, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiServiceTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition+members+pages.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition+members.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition+pages.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition.json, pom.xml
Import/Export pages and members
fix gravitee-io/issues#164
=> feat(export.import): Full import/export of an api

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java
=> feat(api): export api using filename pattern: apiName-apiVersion.json

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewPageEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdatePageEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
=> fix(api): create page without content

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ImportSwaggerDescriptorEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-service/pom.xml, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/SwaggerDescriptorException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerServiceTest.java
=> feat(api): Create an API using a Swagger descriptor URL

gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/AnalyticsRepositoryProxy.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/EventRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformAnalyticsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformEventsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/AnalyticsParam.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/ApiIdsParam.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/DirectionParam.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/EventSearchParam.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/OrderModeParam.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/basic/BasicSecurityConfigurerAdapter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/AnalyticsService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/EventService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EventServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/EventServiceTest.java, pom.xml
This closes gravitee-io/issues#113
=> feat(events-analytics): add events and analytics resources

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/MembershipTypesAllowed.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/mapper/ObjectMapperResolver.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/filter/ApiMembershipTypeFilter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/spring/ServiceConfiguration.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiServiceTest.java
This closes gravitee-io/issues#202
=> Full API descriptor must be restricted to PRIMARY_OWNER, OWNER and administrators

pom.xml
=> feat(policy): Enable / disable a policy rule

gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ApiPermission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/PermissionHelper.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiMembersResource.java
This closes gravitee-io/issues#210
=> feat(api): add transfer API ownership functionality

gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/EventRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformEventsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/EventService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EventServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/EventServiceTest.java
=> feat(repository): Preserve a single method to search for events.

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiListItem.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewViewEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateViewEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/ViewEntity.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/ViewRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ConfigurationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ViewsResource.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/basic/BasicSecurityConfigurerAdapter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ViewService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/DuplicateViewNameException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ViewServiceImpl.java
This closes https://github.com/gravitee-io/issues/issues/112
=> Allows to group list of APIs by views

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewPageEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/PageConfigurationEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/PageEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/PageListItem.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdatePageEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
=> feat(documentation): enable tryit mode on swagger

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPagesResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PageService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
=> feat(page): Dynamic page content using ${}

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> fix(elasticsearch): Normalize Elasticsearch repository configuration

gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/ApiRepositoryProxy.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/ApplicationRepositoryProxy.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/MembershipRepositoryProxy.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/UserRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPagesResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/UserService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiServiceTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApplicationServiceTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/UserServiceTest.java, pom.xml
=> feat(membership): store memberships in a dedicated repository

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java
do not try to convert empty set of apis ou applications
fix gravitee-io/issues#228
=> fix(membership): store memberships in a dedicated repository

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationAnalyticsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationResource.java
This closes gravitee-io/issues#238
=> feat(application) : add application analytics resource

gravitee-management-api-model/src/main/java/io/gravitee/management/model/RegisterUserEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UsersResource.java, gravitee-management-api-security/pom.xml, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/basic/BasicSecurityConfigurerAdapter.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/basic/filter/AuthenticationSuccessFilter.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/basic/filter/JWTAuthenticationFilter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/UserService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/common/JWTHelper.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/UserServiceTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/userRegistration.html, pom.xml
This closes https://github.com/gravitee-io/issues/issues/246
=> Allows to create an account from the rest-api

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ViewEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/enhancer/ViewEnhancer.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ViewsResource.java
This fixes gravitee-io/issues#220
=> fix(view): Do not show views without any API

gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/Container.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(plugin): Do not start if a component is not well started

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
create group during import if not exists
fix gravitee-io/issues#275
=> fix: import/export groups

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/enhancer/ViewEnhancer.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(definition): Use views from API instead of its definition

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ViewsResource.java
=> fix(portal): Views are now sorted alphabetically

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PluginEntity.java
=> fix(plugin): allow plugin with same id

gravitee-management-api-services/gravitee-management-api-services-core/pom.xml, gravitee-management-api-services/gravitee-management-api-services-subscriptions/pom.xml, gravitee-management-api-services/pom.xml, gravitee-management-api-standalone/gravitee-management-api-standalone-container/pom.xml, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/pom.xml
and refactor artifactid
fix gravitee-io/issues#285
=> fix: subscriptions service zip is fat

gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/PermissionHelper.java
=> fix(permission): PO & owner must be able to manage plans

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlansResource.java
=> fix(management-api): List of plans for an API is sorted by order value

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PlanEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/PlanStatus.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlansResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/PlanStatusParam.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/PlanAlreadyClosedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/PlanAlreadyPublishedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/PlanNotYetPublishedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/PlanWithSubscriptionsException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanServiceTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java, pom.xml
=> feat(plan): Manage API plans status

gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/ApplicationRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/Subscription.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/SubscriptionsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApplicationService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApplicationServiceTest.java
=> feat(subscription): api publisher could add app subscription

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java
=> fix(subscription): Mail are send asynchronously

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewTagEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/TagEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateTagEntity.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/TagRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ConfigurationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/TagsResource.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/basic/BasicSecurityConfigurerAdapter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/TagService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/DuplicateTagNameException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TagServiceImpl.java
This closes https://github.com/gravitee-io/issues/issues/318
=> Allows to CRUD sharding tags

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(mail): Add a configuration to enabled / disabled mail sending

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApiNotDeletableException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiServiceTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanServiceTest.java
=> feat(api): An API can not be deleted if there are active plans.

pom.xml
=> feat(gateway): HTTP Compression is enabled by default at the client side

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewPageEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageServiceTest.java
=> fix(page): Creating page is requiring a page's type

gravitee-management-api-model/src/main/java/io/gravitee/management/model/analytics/Timestamp.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/jetty/JettyServerFactory.java
This closes https://github.com/gravitee-io/issues/issues/385
=> Do not tranfer all the timestamps on the response analytics data

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java
This closes gravitee-io/issues#394
=> fix(analytics) : handle no API/Application analytics data

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/bin/gravitee, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/bin/gravitee.bat
=> fix(management-api): Set default JVM options

gravitee-management-api-model/src/main/java/io/gravitee/management/model/InstanceEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/InstanceListItem.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InstanceServiceImpl.java
=> Port instances display

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewPageEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewPlanEntity.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/ApiRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/VerifyApiParam.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java
This closes gravitee-io/issues#418
=> feat(api): enhance create api workflow

gravitee-management-api-model/src/main/java/io/gravitee/management/model/InstanceEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/InstanceListItem.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewTenantEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/TenantEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateTenantEntity.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/TenantRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ConfigurationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/TenantsResource.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/basic/BasicSecurityConfigurerAdapter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/TenantService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/DuplicateTenantNameException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/TenantNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InstanceServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TenantServiceImpl.java, pom.xml
=> feat(gateway): Multi-tenant support

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, pom.xml
=> fix(endpoints): endpoints with same name are allowed

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/userRegistration.html
=> fix(user): Update user registration link

gravitee-management-api-service/pom.xml, gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/pom.xml, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/assembly/distribution.xml
=> chore: Mail 1.4.3 must not be part of the final distribution.

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/spring/EmailConfiguration.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/basic/BasicSecurityConfigurerAdapter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/utils/EnvironmentUtils.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(mail): Additional properties for SMTP configuration

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(import): policies are not imported, only paths

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-services/gravitee-management-api-services-sync/src/main/java/io/gravitee/management/services/sync/SyncManager.java
=> fix(api): Removing picture from deploy event

gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/PageRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalPagesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalResource.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/basic/BasicSecurityConfigurerAdapter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PageService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateOrUpdateWithDefinitionTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageServiceTest_Create.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageServiceTest_FindByApi.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageServiceTest_FindMaxPageOrderByApi.java
=> feat(pages): add portal pages

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UserResource.java
=> fix(profil): Add default api_consumer role for authenticated user

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiListItem.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix: get api description on apis.findAll()

gravitee-management-api-services/gravitee-management-api-services-sync/src/main/java/io/gravitee/management/services/sync/SyncManager.java
=> fix(sync): Sync service must not take care about sharding tags

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, pom.xml
=> feat(plugin): Allow to load plugins from multiple registries

gravitee-management-api-service/pom.xml
=> chore: Upgrade Swagger dependency to latest

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java
=> fix(api): By default, export all data

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java
=> fix(plan): Force API refresh after closing a plan

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/InvalidDataException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(api): Check the associated group validity when updating API

gravitee-management-api-model/src/main/java/io/gravitee/management/model/analytics/query/LogQuery.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequest.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequestItem.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApplicationRequest.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApplicationRequestItem.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/LogItem.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/SearchLogResponse.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/LogRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiLogsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationLogsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/LogsParam.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/LogsService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java, pom.xml
=> feat(log): Request /response analysis

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiMetadataEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiModelEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/MetadataEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/MetadataFormat.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewApiMetadataEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewMetadataEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/PageEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApiMetadataEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateMetadataEntity.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/MetadataRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiMetadataResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPagesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ConfigurationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/MetadataResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiMetadataService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/MetadataService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApiMetadataNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/DuplicateMetadataNameException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiMetadataServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MetadataServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java
=> Add management of metadatas

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(sharding): Do not use tags field from Api repository model entity

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
This closes https://github.com/gravitee-io/issues/issues/154
=> Do not ask for sync if policy description is modified

gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/jetty/JettyConfiguration.java, gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/jetty/JettyServerFactory.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
Added code to specify to which IP/hostname to bind Jetty to.
fix gravitee-io/issues#621
=> feat(jetty): customize jetty binding IP/host

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiEntity.java
=> fix(api): Deployment not required when API visibility has changed

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiListItem.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java
=> fix(api): Add list of views associated to each API

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiListItem.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApiEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, pom.xml
=> feat(api): Associate labels to an API

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java
=> fix(api): Add context_path information into the API object

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/Subscription.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/SubscriptionsResource.java
=> feat(subscription): Add a link to the API and the API's version

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/bind/AuthenticationBinder.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/AbstractAuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/AuthenticationSource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/GoogleAuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/JerseySpringTest.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/authentication/impl/AuthenticationProviderManagerImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(portal): Add custom OAuth2 authentication provider

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
=> fix(analytics): Analytics service must not be transactional

gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/DynamicPropertyUpdater.java
=> fix(dynamic-properties): Check that current properties are not null

gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java, pom.xml
=> feat(log): Add a message settled by the gateway in case of error

gravitee-management-api-idp/gravitee-management-api-idp-repository/src/main/java/io/gravitee/management/idp/repository/RepositoryIdentityProvider.java, gravitee-management-api-idp/gravitee-management-api-idp-repository/src/main/java/io/gravitee/management/idp/repository/lookup/RepositoryIdentityLookup.java
=> fix(user): Search for social user

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/bin/gravitee, pom.xml
=> feat(node): Start the management-api as a daemon and create a pid file

gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
=> feat(log): Add gateway identifier

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/pom.xml, gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/DynamicPropertiesService.java, gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/provider/http/HttpProvider.java, gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/provider/http/vertx/VertxCompletableFuture.java, gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/test/java/io/gravitee/management/services/dynamicproperties/provider/http/HttpProviderTest.java, gravitee-management-api-services/gravitee-management-api-services-healthcheck/pom.xml, gravitee-management-api-services/gravitee-management-api-services-subscriptions/pom.xml, gravitee-management-api-services/gravitee-management-api-services-sync/pom.xml, gravitee-management-api-services/pom.xml
=> fix(service): Move HTTP client from AHC to Vert.x

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java
=> fixi(permissions): unauthenticated user can diaply public apis

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/AuthenticationSuccessFilter.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> fix(role): Fix several issues with role management

gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java
=> Fix : TU break on windows

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java
=> fix(email): sometimes email are not sent, sometimes with bad content

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiGroupMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyExpired.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyRevoked.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/applicationGroupMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/applicationMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionApproved.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionReceived.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionRejected.html
=> fix(email): bad templates

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/bin/gravitee, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/bin/gravitee.bat
=> fix(launcher): Disable Vertx cache

gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/DynamicPropertyUpdater.java
=> fix(dynamic properties): add log in case of duplicate keys

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPagesResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/JerseySpringTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/ApiPagesResourceAdminTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/ApiPagesResourceNotAdminTest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PageService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/RoleServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_IsDisplayableTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/RoleService_HasPermissionTest.java
=> fix(pages): Admin user cannot see documentation pages

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java
=> Application owners must be notify when their subscriptions are closed after the close of a plan

gravitee-management-api-model/src/main/java/io/gravitee/management/model/SubscriptionEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/Subscription.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiKeysResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/SubscriptionsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiKeyService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/builder/EmailNotificationBuilder.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiKeyServiceTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyRevoked.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionClosed.html, pom.xml
=> Better management of closing plan : set a closed date on subscriptions and send a clearer email to all subscribers of the plan

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> fix(email): Subject property

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanServiceTest.java
=> fix: Could not change plans order

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/spring/EmailConfiguration.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java
=> fix: the email 'from' is not set

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyExpired.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/applicationGroupMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/applicationMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/groupMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionApproved.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionClosed.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionReceived.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionRejected.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/userRegistration.html
=> Improve the email message of a subscription request

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/AbstractAuthenticationResource.java
=> fix(authentication): Apply httpOnly flag on cookie

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPagesResource.java
=> Override base url of the swagger descriptor file

gravitee-management-api-services/gravitee-management-api-services-healthcheck/src/main/java/io/gravitee/management/services/healthcheck/probe/ManagementApiProbe.java
=> Use the 'http.host' config if defined, else 'localhost'

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/filter/PermissionsFilter.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java
=> fix(roles): Check admin rights

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java
=> fix(application): update application with creation date

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java
=> fix(groups): Event rules are not updated

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java
=> fix(members): Set the primary_owner before updating the actual one

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyExpired.html
=> Display expiration date on revocation's email

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/AbstractAuthenticationResource.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/cookies/JWTCookieGenerator.java
=> Allows to configure the max age on the Authorization's cookie

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java
=> The default API's picture disappear on save

pom.xml
=> fix(health-check): Do not parse data if service is disabled

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java
=> fix(notification): wrong name used in emails for new subscriptions

gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequest.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApplicationRequest.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/extended/Request.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/extended/Response.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/LogRepositoryProxy.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java, pom.xml
=> feat(logging): Add full log service

gravitee-management-api-model/src/main/java/io/gravitee/management/model/MemberEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateOrUpdateWithDefinitionTest.java
=> fix(api): import members if necessary

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/applicationMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/groupMember.html
=> fix(notification): owner is not define in email templates

gravitee-management-api-rest/pom.xml, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/AbstractAuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/oauth2/AuthorizationServerConfigurationParser.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/oauth2/ExpressionMapping.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/oauth2/ServerConfiguration.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/oauth2/UserMapping.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/JerseySpringTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/auth/Oauth2TestAuthenticationProviderManager.java, gravitee-management-api-rest/src/test/resources/io/gravitee/management/rest/resource/jwt.properties, gravitee-management-api-rest/src/test/resources/oauth2/json/token_response_body.json, gravitee-management-api-rest/src/test/resources/oauth2/json/user_info_401_response_body.json, gravitee-management-api-rest/src/test/resources/oauth2/json/user_info_response_body.json, gravitee-management-api-rest/src/test/resources/oauth2/json/user_info_response_body_no_matching.json, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/RoleServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, pom.xml
=> Assign automatically group from oauth user info

gravitee-management-api-model/src/main/java/io/gravitee/management/model/EventEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EventServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/EventServiceTest.java
=> Display the complete name instead of just the username

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewTicketEntity.java, gravitee-management-api-rest/pom.xml, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformTicketsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/EmailNotification.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/TicketService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/builder/EmailNotificationBuilder.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/EmailRequiredException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/SupportUnavailableException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InitializerServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MetadataServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TicketServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/TicketServiceTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/supportTicket.html, pom.xml
=> Contact screen to send an email to the support team

gravitee-management-api-model/src/main/java/io/gravitee/management/model/healthcheck/Log.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/healthcheck/Request.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/healthcheck/Response.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/healthcheck/SearchLogResponse.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/healthcheck/Step.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/HealthCheckRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiHealthResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/HealthCheckServiceImpl.java
=> feat(healthcheck): Store more information in case of HC fail

gravitee-management-api-services/gravitee-management-api-services-healthcheck/src/main/java/io/gravitee/management/services/healthcheck/probe/ManagementApiProbe.java
=> fix(healthcheck): Default configuration

gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/ApiKeyRepositoryProxy.java
=> feat(apikey): New method for api-key refresh improvements

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlanSubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlansResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PlanService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanService_CloseTest.java
=> fix(subscription): could not close subscription as a primary owner

gravitee-management-api-services/gravitee-management-api-services-core/src/main/java/io/gravitee/management/services/http/HttpServer.java, gravitee-management-api-services/gravitee-management-api-services-core/src/main/java/io/gravitee/management/services/http/configuration/HttpServerConfiguration.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> closes gravitee-io/issues#791

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
=> refactor(reporter): Log and metrics reporting

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(api): remove subscriptions when an api is deleted

gravitee-management-api-services/gravitee-management-api-services-healthcheck/src/main/java/io/gravitee/management/services/healthcheck/probe/ManagementRepositoryProbe.java
=> fix(healthcheck): Rename management probe

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlansResource.java
=> fix(plan): unpublished plans must not be accessible to everyone

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
=> issue #853 : Add default roles to created user when mapping groups 

appveyor.yml, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java, pom.xml
=> chore: add windows build based on rAapprVveyor

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPagesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlansResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalPagesResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/GroupService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/GroupService_IsUserAuthorizedToAccessTest.java
=> feat(pages): add group restrictions on portal pages

pom.xml
=> chore: Upgrade vert.x to 3.5.0

gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequest.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApplicationRequest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
=> feat(log): Improve log description

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiListItem.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewRatingAnswerEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewRatingEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/RatingAnswerEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/RatingEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/RatingSummaryEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateRatingEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ApiPermission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/RatingAnswerRepositoryProxy.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/RatingRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiRatingResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/RatingService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApiRatingUnavailableException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/RatingAlreadyExistsException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/RatingNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/RatingServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/RatingServiceTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, pom.xml
This closes gravitee-io/issues#840
=> Implementation of rating of APIs

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java
=> Allows to close a subscription

gravitee-management-api-services/gravitee-management-api-services-subscriptions/src/main/java/io/gravitee/management/services/subscriptions/ScheduledSubscriptionsService.java, gravitee-management-api-services/gravitee-management-api-services-subscriptions/src/test/java/io/gravitee/management/services/subscriptions/ScheduledSubscriptionsServiceTest.java
=> fix(subscription): do not close subscription with end date in the future

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UserResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AbstractService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AuditServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/RoleServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java
=> Allows to create audit on initialization service with a system user

gravitee-management-api-service/src/main/java/io/gravitee/management/service/RoleService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InitializerServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/RoleServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/RoleService_CreateOrUpdateSystemRolesTest.java
=> fix(roles): do not reset system permissions on each reboot

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java
=> fix(plan): Set updatedAt property when publishing plan

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AuditServiceImpl.java
=> fix(audit): Do not look into audit properties if this later is optional

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InitializerServiceImpl.java
=> fix(init): create default role in addition to system roles

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlansResource.java
=> fix(plans): Restricted plans are not visible by the admin

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewViewEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateViewEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/ViewEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/enhancer/ViewEnhancer.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ViewsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ViewService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InitializerServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ViewServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ViewService_CreateTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ViewService_DeleteTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ViewService_FindTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ViewService_UpdateTest.java, pom.xml
=> feat(views): make views sortable, hidden and choose the default one

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> chore: Set default local configuration for ES connector over HTTP

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationMembersResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/MembershipService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java
=> feat(members): change the application PO

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/RoleEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiMembersResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationMembersResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/MembershipService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java
=> feat(member): set the new role of the old primaryOwner

gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ApiPermission.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InitializerServiceImpl.java, pom.xml
=> feat(endpoint-dicsovery): Add new discovery feature and dedicated role

gravitee-management-api-model/src/main/java/io/gravitee/management/model/analytics/Bucket.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiHealthResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/AnalyticsAverageParam.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/AnalyticsAverageTypeParam.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/HealthCheckService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/HealthCheckServiceImpl.java
This closes gravitee-io/issues#889
=> feat: Added a chart to display global Health Check average

gravitee-management-api-model/src/main/java/io/gravitee/management/model/documentation/PageQuery.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/plan/PlanQuery.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PageService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PlanService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateOrUpdateWithDefinitionTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition+plans.json
=> fix(import): do not duplicate plans and pages on import

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/bin/gravitee
Fixes https://github.com/gravitee-io/issues/issues/944
=> fix(cygwin-classpath): Added classpath conversion

gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ApiPermission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ApplicationPermission.java
=> fix(permission): duplicate permissions

gravitee-management-api-rest/pom.xml, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java, pom.xml
Closes  #310    #309   gravitee-io/issues#965
=> fix(oauth2): Oauth2-Maper is not support json path search

gravitee-management-api-model/src/main/java/io/gravitee/management/model/plan/PlanQuery.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java
=> fix: could not create api from scratch with plan

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/GitHubAuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/GoogleAuthenticationResource.java
=> fix(authentication): Set authentication user in security context

gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java
=> fix(ldap): Set baseDn explicitly for each LDAP search requests.

gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/DynamicPropertyUpdater.java
=> feat(dynamic-properties): add apiId in all logs

gravitee-management-api-model/src/main/java/io/gravitee/management/model/TaskEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/TaskType.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/pagedresult/Metadata.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/PagedResult.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UserResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UsersResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/ApiPagesResourceNotAdminTest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PermissionService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/TaskService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PermissionServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TaskServiceImpl.java, pom.xml
=> feat(taks): add a task list for each user

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AbstractService.java
=> fix(registration): user signup fails

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/PreconditionFailedException.java
This closes gravitee-io/issues#999
=> feat: Allows to handle concurrent modifications on API

gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> Configurable objectclass in LDAP search for users

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewExternalUserEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateUserEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java
closes https://github.com/gravitee-io/issues/issues/1020
closes https://github.com/gravitee-io/gravitee-management-rest-api/pull/329
=> fix(oauth2): Update firstname and lastname after obtaining profile

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UsersResource.java
Closes gravitee-io/issues#1036
=> fix(user): If user picture is an url, send a redirection to the uri

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/AbstractAuthenticationResource.java
Closes gravitee-io/issues#1035
=> fix(role): Authorities are set for oauth / social authentication

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java
=> feat(geoip): Add generic metadata when convert GroupByResponse

pom.xml
=> fix(failover): set the default timeout > 0

gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/DynamicPropertyUpdater.java
=> fix(properties): sort dynamic properties to avoid redeploy

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> fix(cors): wrong default CORS configuration

gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/provider/http/mapper/JoltMapper.java
=> fix(dynamic properties): accept array value as input

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java
Closes gravitee-io/issues#1062
=> fix(subscription): An application can subscribe to different APIs

gravitee-management-api-model/src/main/java/io/gravitee/management/model/UserEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AuditServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyExpired.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyRevoked.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/applicationMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/groupMember.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionApproved.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionClosed.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionReceived.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionRejected.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/supportTicket.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/userRegistration.html
=> fix(audit): use the display name

pom.xml
Closes gravitee-io/issues#1092
=> chore: Upgrade Vert.x to 3.1.5

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewTopApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/TopApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateTopApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/ParameterRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ConfigurationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/TopApisResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ParameterService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/TopApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ParameterAlreadyExistsException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ParameterNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InitializerServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ParameterKeys.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ParameterServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TagServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TopApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ParameterServiceTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/TopApiServiceTest.java, pom.xml
This closes gravitee-io/issues#932
=> feat: allows to configure top APIs displayed on portal

pom.xml
Closes gravitee-io/issues#1056
=> feat(tenant): An endpoint can be associated to multiple tenants

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformAnalyticsResource.java
=> feat(dashboard): filter global dashboard with authorized API/APP

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/gravitee-management-api-standalone-distribution-zip/src/main/assembly/distribution.xml
=> fix: add missing assets

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/spring/EnvironmentBeanFactoryPostProcessor.java
=> feat(configuration): allow _ for envvar

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TopApiServiceImpl.java
This closes gravitee-io/issues#1131
=> fix: check top api parameter when deleting top apis

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AuditServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/RatingServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TransactionalService.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/RatingServiceTest.java
This closes gravitee-io/issues#344
=> fix: do not rollback when a business exception occurs

pom.xml
Closes gravitee-io/issues#1137
=> chore: Upgrade plugin-core dependency

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> 404 subscription not found while deleting an API

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/spring/EnvironmentBeanFactoryPostProcessor.java
=> fix(config): be able to set array in envvar

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java
This closes gravitee-io/issues#1166
=> feat: Allows to filter top APIs by visibility/membership

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(api): do not fail on the first start

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java
Closes gravitee-io/issues#1132
=> [management] use HashMap to replace Hashtable

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ImportSwaggerDescriptorEntity.java, gravitee-management-api-service/pom.xml, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_PrepareTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_TransformTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/openapi.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/openapi.yaml, pom.xml
=> fix(swagger): support openapi v3

gravitee-management-api-idp/gravitee-management-api-idp-core/src/main/java/io/gravitee/management/idp/core/authentication/impl/CompositeIdentityManager.java, gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java
This closes gravitee-io/issues#1174
=> fix: Unable to lookup user with reference sometimes

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/Subscription.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/SubscriptionsResource.java
=> fix(subscription): display the subscribedBy name

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
=> feat(): forward exceptions

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/CurrentUserResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java
=> fix(user): update user avatar

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewSubscriptionEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/SubscriptionEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/Subscription.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/SubscriptionService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionApproved.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionReceived.html, pom.xml
=> feat(subscription): add a reason on accept and on request

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
Closes gravitee-io/issues#1183
=> fix(documentation): Tranform documentation only when there is a TryItURL

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AuditServiceImpl.java
=> feat(audit): display user name if available

gravitee-management-api-idp/gravitee-management-api-idp-repository/src/main/java/io/gravitee/management/idp/repository/lookup/RepositoryIdentityLookup.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UserGroupEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/MembershipRepositoryProxy.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/UserRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GroupMembersResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/RoleUsersResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UserResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UsersResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/GroupMemberResourceTest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/GroupService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/MembershipService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/UserService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/RoleDeletionForbiddenException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/StillPrimaryOwnerException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/RoleServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/GroupService_FindByEventTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/RoleService_CreateOrUpdateSystemRolesTest.java
=> feat(user): add user management

gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/DynamicPropertyUpdater.java
=> fix(dynprop): lost labels on update

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/supportTicket.html
Closes gravitee-io/issues#1202
=> fix(bug): can't submit a support ticket

pom.xml
=> fix(http): Handle properly unknown HTTP method

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/UserServiceTest.java
Closes https://github.com/gravitee-io/issues/issues/1209
=> fix(bug): User registration fails

gravitee-management-api-model/src/main/java/io/gravitee/management/model/GroupEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/GroupPermission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/Permission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/filter/PermissionsFilter.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GroupMemberResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GroupMembersResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GroupResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GroupsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UserResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/MembershipService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/RoleServiceImpl.java, pom.xml
=> feat(group): Delegate the management of a group

gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/jetty/JettyConfiguration.java, gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/jetty/JettyServerFactory.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(jetty): enable https only mode

gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java
This closes gravitee-io/issues#1231
=> fix: Import API does not work when LDAP is not reachable

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(report): Index per type support

gravitee-management-api-idp/gravitee-management-api-idp-repository/src/main/java/io/gravitee/management/idp/repository/authentication/RepositoryAuthenticationProvider.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewExternalUserEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UserResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/UserService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/builder/EmailNotificationBuilder.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/EmailFormatInvalidException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/UserNotInternallyManagedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notification/PortalHook.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/UserServiceTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/notifications/portal/PORTAL.PASSWORD_RESET.yml, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/passwordReset.html
This closes gravitee-io/issues#1230
=> feat: Allows to reset a password of an internal user

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformAnalyticsResource.java
Closes gravitee-io/issues#1249
=> fix(analytics): Remove extra filter if empty

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/MembershipService_AddOrUpdateMemberTest.java
=> fix(groups): do not allow PO as default user role

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ImportSwaggerDescriptorEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_PrepareTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_TransformTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/openapi.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/openapi.yaml, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/swagger-v1.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/swagger-v2.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/swagger-v2.yaml
be able to create an api with an openapi definition
fix gravitee-io/issues#1246
=> feat(api): import openapi

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java
Closes gravitee-io/issues#1234
=> fix(subscription): Set the request message into the subscription

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TaskServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/TaskServiceTest.java
=> fix(tasks): optimize how to get get user tasks 

gravitee-management-api-standalone/gravitee-management-api-standalone-bootstrap/pom.xml
Closes gravitee-io/issues#1257
=> chore: Management API Boostrapper is now executable

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/CurrentUserResource.java
This closes gravitee-io/issues#1264
=> feat: allows to limit size of uploaded images

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/CurrentUserResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/AbstractAuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/GitHubAuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/GoogleAuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java
This closes gravitee-io/issues#1259
=> fix: Allows to define cookie on a specific domain, path

gravitee-management-api-idp/gravitee-management-api-idp-core/src/main/java/io/gravitee/management/idp/core/plugin/impl/IdentityProviderManagerImpl.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/spring/EnvironmentBeanFactoryPostProcessor.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/authentication/impl/AuthenticationProviderManagerImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/utils/EnvironmentUtils.java, pom.xml
=>  feat(config): support different type of configuration

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
=> feat(jwt): Warn if the default secret is used

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyExpired.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyRevoked.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionApproved.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionClosed.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionReceived.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionRejected.html
=> fix(management): remove owner name on templates 

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiHealthResource.java
This closes gravitee-io/issues#1083
=> fix: take care of dates on HC zoom

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiHealthResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/healthcheck/LogsParam.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/HealthCheckService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/HealthCheckServiceImpl.java, pom.xml
This closes gravitee-io/issues#1240
=> feat: allows to display HC status transitions

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/GitHubAuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/GoogleAuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/oauth2/AuthorizationServerConfigurationParser.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/utils/EnvironmentUtils.java
=> fix(social): social configuration cannot be read

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> chore(yml): Remove usage of env variables from gravitee.yml

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InitializerServiceImpl.java
This closes gravitee-io/issues#1297
=> fix: A user with role USER is not able to subscribe to an API plan

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
This closes gravitee-io/issues#1295
=> fix: Take care of visibility when importing an API

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
This closes gravitee-io/issues#818
=> fix: Better handling error when looking for APIs

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/HealthCheckServiceImpl.java, pom.xml
=> feat(gateway): Manage group of endpoints

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformAnalyticsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformEventsResource.java
=> fix(analytics): filter tenant chart, response status by apis

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TaskServiceImpl.java
=> fix(tasks): a user without apis must not have tasks

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java
This closes gravitee-io/issues#1357
=> fix: The PNG images included in emails are not correctly mime typed

gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateUserEntity.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/listener/AuthenticationSuccessListener.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java
=> fix(user): update user profile

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApiEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EventServiceImpl.java, gravitee-management-api-services/gravitee-management-api-services-sync/src/main/java/io/gravitee/management/services/sync/SyncManager.java, pom.xml
This closes gravitee-io/issues#1312
=> feat: display top paths/resources in analytics

gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/WebhookNotifierServiceImpl.java
This closes gravitee-io/issues#1358
=> fix: Hooks notification does not work properly on support ticket without parameters

gravitee-management-api-services/gravitee-management-api-services-sync/src/main/java/io/gravitee/management/services/sync/SyncManager.java
Closes gravitee-io/issues#1367
=> fix(sync): Optimize sync API deployment process

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ViewResource.java
=> fix(views): permit access to public views

gravitee-management-api-rest/pom.xml, gravitee-management-api-standalone/gravitee-management-api-standalone-container/pom.xml, pom.xml
This closes gravitee-io/issues#1382
=> chore: Upgrade Jersey/Jetty dependencies

gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/authentication/LdapAuthenticationProviderConfigurer.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/SecurityConfiguration.java, pom.xml
This closes gravitee-io/issues#1384
=> chore: Upgrade Spring security dependencies

pom.xml
This closes gravitee-io/issues#1385
=> chore: Upgrade Freemarker dependencies

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_FindByUserTest.java
=> fix(apis): find apis by user

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java
=> fix(config): return empty list for oauth2 scopes

gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/LogRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiLogsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationLogsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/LogsService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java, pom.xml
closes gravitee-io/issues#1412
=> feat(log): add log timestamp to select elasticsearch indices

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/CurrentUserResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/CurrentUserResourceTest.java
=> fix: using an empty string if the password is null to avoid Exception

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformAnalyticsResource.java
=> fix(dashboard): filter apis even if the user has no apis

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiQualityMetricsEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/PortalConfigEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/parameters/Key.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/QualityMetricsService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApiQualityMetricsDisableException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/QualityMetricsServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetric.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetricDescription.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetricFunctionalDocumentation.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetricHealthcheck.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetricLabels.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetricLoader.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetricLogo.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetricTechnicalDocumentation.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetricViews.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/spring/ServiceConfiguration.java, gravitee-management-api-service/src/main/resources/META-INF/spring.factories, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiQualityMetricDescriptionTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiQualityMetricFunctionalDocumentationTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiQualityMetricHealthcheckTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiQualityMetricLabelsTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiQualityMetricLogoTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiQualityMetricTechnicalDocumentationTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiQualityMetricViewsTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/QualityMetricsService_GetApiMetricsTest.java
=> feat(quality): add api quality metrics

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(api.list) a user with no apis see everything

gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ManagementPermission.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InitializerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/RoleService_CreateOrUpdateSystemRolesTest.java
=> fix(perms) remove unused perms

gravitee-management-api-model/src/main/java/io/gravitee/management/model/UserMembership.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UserMembershipList.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiQuery.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GroupResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UserResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/GroupService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/MembershipService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApplicationService_FindByGroupTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/MembershipService_FindUserMembershipTest.java
=> feat(management): show apis and apps for a user or a group

gravitee-management-api-model/src/main/java/io/gravitee/management/model/MessageChannel.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/MessageEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/MessageRecipientEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ApiPermission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ManagementPermission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ConfigurationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/MessagesResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/EmailNotification.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/MessageService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/builder/EmailNotificationBuilder.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/MessageEmptyException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/MessageRecipientFormatException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MessageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notification/ApiHook.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notification/Hook.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notification/PortalHook.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/MessageService_GetRecipientIdsTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/RoleService_CreateOrUpdateSystemRolesTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/genericMessage.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/notifications/portal/API.MESSAGE.yml, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/notifications/portal/PORTAL.MESSAGE.yml
=> feat(messages): add the message feature

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/JWTAuthenticationFilter.java
=> fix(jwt): reset token if invalid

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PageType.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_FindByApiTest.java
This closes gravitee-io/issues#1428
=> feat: remove RAML support

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#1459
=> feat(http): Let the user to configure HSTS headers

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/oauth2/AuthorizationServerConfigurationParser.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/oauth2/ExpressionMapping.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/oauth2/ServerConfiguration.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#1058
=> feat(role): Add role mapping for OAuth2 authentication

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiListItem.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java
=> feat(apis): improve the api list display

gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
=> feat(logs): improve api logs

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/Api1_15VersionSerializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiCompositeSerializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiDefaultSerializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiSerializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/spring/ServiceConfiguration.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportMultipleEndpointGroups-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithouGroup.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans.json
Closes gravitee-io/issues#1503
=> feat(api): export API definition for a specific Gravitee.io APIM version

gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/Api1_15VersionSerializer.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java, pom.xml
Closes gravitee-io/issues#1482
=> feat(logging): Define a condition to log a request

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
Closes gravitee-io/issues#1527
=> fix(log): Decode log's path with non-encoded character

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(history): errors on rollback

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/configuration/SearchEngineConfiguration.java
=> fix(search): wrong default search index dir

gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequest.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApplicationRequest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java, pom.xml
Closes gravitee-io/issues#1536
=> feat(analytics): Add Host HTTP header into analytics

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscribedResource.java
Closes gravitee-io/issues#1539
=> feat(logs): Add filtering to search for application's logs

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PortalConfigEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/header/ApiHeaderEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/header/NewApiHeaderEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/header/UpdateApiHeaderEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/parameters/Key.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/PortalPermission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/ApiHeaderRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiHeaderResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiHeadersResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ConfigurationResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiHeaderService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApiHeaderNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiHeaderServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/upgrade/DefaultApiHeaderUpgrader.java
=> feat(api-portal-header): edit headers

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
Closes gravitee-io/issues#1577
=> fix(search): Search engine can be called by an anonymous user

gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdatePageEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPageResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalPagesResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PageService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
=> feat: Update partially the documentation pages

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/DictionaryServiceImpl.java
=> fix(dict): stop polling dictionary on delete

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TaskServiceImpl.java
=> fix(tasks): do not look for api by groups if no groups available

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java
Closes gravitee-io/issues#1593
=> fix(swagger): Datetime properties must be convert as long (int64)

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/AlreadyPrimaryOwnerException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/MembershipService_AddOrUpdateMemberTest.java
=> fix(members): do not override primary owner role

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/provider/UriBuilderRequestFilter.java
Closes gravitee-io/issues#1610
=> fix(api): Preserve x-forward-* headers to construct API's picture URL

gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/authentication/UserDetailsContextPropertiesMapper.java
Closes gravitee-io/issues#1587
=> fix(ldap): Attributes are not mapped to the correct user's field

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/searcher/ApiDocumentSearcher.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/transformer/ApiDocumentTransformer.java
Closes gravitee-io/issues#1626
=> feat(search): APIs can be searched by their exact name

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationNotificationSettingsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PermissionServiceImpl.java
Closes gravitee-io/issues#1639
=> fix(notification): We must check for an empty referenceId

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlansResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/PlanStatusParam.java
=> fix(plan): access plan management with only read permission

gravitee-management-api-idp/gravitee-management-api-idp-core/src/main/java/io/gravitee/management/idp/core/authentication/impl/CompositeIdentityManager.java
closes gravitee-io/issues#1668
=> feat(idp): log user reference serializer errors

gravitee-management-api-services/gravitee-management-api-services-sync/src/main/java/io/gravitee/management/services/sync/SyncManager.java
=> fix(sync): do not fail the sync process on NPE

gravitee-management-api-model/src/main/java/io/gravitee/management/model/MessageEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/notification/GenericNotificationConfigEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GenericNotificationConfigServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MessageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/WebNotifierService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/WebNotifierServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/WebhookNotifierServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, pom.xml
=> feat(proxy): add global proxy

gravitee-management-api-model/src/main/java/io/gravitee/management/model/MediaEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/PortalConfigEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/parameters/Key.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/MediaRepositoryProxy.java, gravitee-management-api-rest/pom.xml, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiMediaResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalMediaResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/MediaService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/UploadUnAuthorized.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MediaServiceImpl.java, pom.xml
=> feat(portal): Allows to persist images to use it on documentation pages

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#1687
=> chore: Update documentation from gravitee.yml

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/RoleUsersResource.java
=> fix(role): do not freeze when adding or removing a member of a role

gravitee-management-api-model/src/main/java/io/gravitee/management/model/configuration/identity/am/AMIdentityProviderEntity.java
Closes gravitee-io/issues#1704
=> fix(identity): Logout URL for Gravitee.io AM is not correct

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
This closes gravitee-io/issues#1714
=> fix: Alert should be disabled by default

gravitee-management-api-service/src/main/java/io/gravitee/management/service/builder/EmailNotificationBuilder.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionCreated.html
This closes gravitee-io/issues#1718
=> fix: No hook template for application on a new subscription

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
This closes https://github.com/gravitee-io/issues/issues/1721
=> doc: Add description for the default plugin config

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/gravitee-management-api-standalone-distribution-zip/src/main/assembly/distribution.xml, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/assembly/distribution.xml
Closes gravitee-io/issues#1723
=> chore: Include the data dir by default

gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java
=> fix(email): No hook template for API on a closed subscription

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/identity/IdentityProviderServiceImpl.java
This closes gravitee-io/issues#1738
=> fix: The idp type is lost on update

gravitee-management-api-model/src/main/java/io/gravitee/management/model/platform/plugin/PluginEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ServiceDiscoveryResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ServicesDiscoveryResource.java, gravitee-management-api-service/pom.xml, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ServiceDiscoveryService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ServiceDiscoveryNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/FetcherServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PolicyServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/plaftform/plugins/ServiceDiscoveryServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/spring/ServiceConfiguration.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PolicyServiceTest.java, pom.xml
Closes gravitee-io/issues#1701
=> feat(discovery): Add service discovery as a plugin support

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AuditServiceImpl.java
Closes gravitee-io/issues#1755
=> fix(audit): Get the displayname of the user

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, pom.xml
Closes gravitee-io/issues#1658
=> feat(audit): Add event for API rollback

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java
Closes gravitee-io/issues#1746
=> fix(subscription): Add service to close an application's subscription

pom.xml
=> fix(authentication): secure all routes if needed

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlansResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PlanService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/PlanAlreadyDeprecatedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanService_DepreciateTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java
Closes gravitee-io/issues#1762
=> feat(plan): A plan can be depreciate to close subscriptions

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
This closes gravitee-io/issues#1788
=> fix: User dn pattern configuration name incorrect in yml

.gitignore, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java
This closes gravitee-io/issues#1785
=> fix: Better handling of swagger descriptor with wrong format

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java
=> fix(email): wrong subject on reset password

gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/authentication/LdapAuthenticationProvider.java, gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/authentication/UserDetailsContextPropertiesMapper.java, gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java
Closes gravitee-io/issues#1804
=> fix(ldap): Support for complex LDAP query

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiKeyEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/SubscriptionEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/Subscription.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/SubscriptionService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/builder/EmailNotificationBuilder.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/SubscriptionNotPausableException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/SubscriptionNotPausedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notification/ApiHook.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notification/ApplicationHook.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/notifications/portal/API.SUBSCRIPTION_PAUSED.yml, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/notifications/portal/APPLICATION.SUBSCRIPTION_PAUSED.yml, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionPaused.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/subscriptionResumed.html
Closes gravitee-io/issues#1753
=> feat(souscription): A subscription can be paused and resumed

gravitee-management-api-model/src/main/java/io/gravitee/management/model/EntrypointEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewEntryPointEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateEntryPointEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ManagementPermission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/EntrypointRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ConfigurationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/EntrypointsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalEntryPointsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/EntrypointService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ParameterService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/EntrypointNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/EntrypointTagsAlreadyExistsException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EntrypointServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ParameterServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/identity/IdentityProviderServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/EntrypointServiceTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/RoleService_CreateOrUpdateSystemRolesTest.java
This closes gravitee-io/issues#1706
=> feat: display entrypoints by API sharding tags

pom.xml
This closes gravitee-io/issues#1766
=> feat: Better handling of character escaping on analytics

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiMetadataServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MetadataServiceImpl.java
=> fix(metadata): unable to create a metadata

gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetricFunctionalDocumentation.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/quality/ApiQualityMetricTechnicalDocumentation.java
=> fix(quality): Quality: pages inside a folder are not taking account

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/KeylessPlanAlreadyPublishedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java
=> fix(plan) a depreciate plan cannot be redeployed

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PageEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPageResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalPagesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/RoleScopesResource.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, pom.xml
This closes gravitee-io/issues#1825
=> fix: Add a link to the git repository defined on a documentation page

gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java
=> fix(email): Incorrect email subject on new subscription

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewViewEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateViewEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/ViewEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractViewResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ViewResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ViewsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ViewService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ViewServiceImpl.java
closes gravitee-io/issues#1821
=> feat(view): add picture to a portal view

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java
Closes gravitee-io/issues#1842
=> fix(apikey): Expiration date can be overriden

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
This closes gravitee-io/issues#1825
=> feat: Add a link to the git repository defined on a documentation page

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PlanEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/processor/PlanSynchronizationProcessor.java, pom.xml
=> fix(plan) do not redeploy api on every plan modification

gravitee-management-api-model/src/main/java/io/gravitee/management/model/analytics/query/AbstractQuery.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
=> fix(analytics): change the end date of the timeframe

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PortalConfigEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/parameters/Key.java, gravitee-management-api-service/pom.xml, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_Update_DefaultLoggingMaxDurationTest.java
=> fix(logging): add a max duration at the platform level

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ImportSwaggerDescriptorEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/NewSwaggerApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/SwaggerPath.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/SwaggerVerb.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/SwaggerService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_PrepareTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/mock/api-with-examples.yaml, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/mock/callback-example.yaml, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/mock/link-example.yaml, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/mock/petstore-expanded.yaml, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/mock/petstore.yaml, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/mock/uspto.yaml
This closes gravitee-io/issues#1567
=> feat: Create mocks in API imported from swagger/OAI

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
This closes gravitee-io/issues#1929
=> fix: Path mapping is not created when importing a swagger/oai

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_PrepareTest.java
This closes gravitee-io/issues#1955
=> fix: Response example of OAI is not well created on a specific case

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java
=> fix(settings) unable to save settings

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ImportPageEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/PageType.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/descriptor/GraviteeDescriptorDocumentationEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/descriptor/GraviteeDescriptorEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/descriptor/GraviteeDescriptorPageEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPagesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/FetchersResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalPagesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/FetchersParam.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/FetcherService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/GraviteeDescriptorService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PageService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/GraviteeDescriptorReadException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/GraviteeDescriptorVersionException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/FetcherServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GraviteeDescriptorServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/upgrade/SearchIndexUpgrader.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateOrUpdateWithDefinitionTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/GraviteeDescriptorService_ReadTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_CreateTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_ImportDescriptorMockFetcher.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_ImportDescriptorTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_ImportDirectoryMockFetcher.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_ImportDirectoryTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_MockDescriptorFetcherConfiguration.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_MockFilesFetcherConfiguration.java
=> feat(tree): fetch pages recursively

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java
=> fix(email): do not load local image resources if src tag is an absolute http url

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/provider/NotAllowedExceptionMapper.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java
=> feat(): handle 405 status code

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
This closes gravitee-io/issues#1984
=> fix: CORS issues when modifying page order or publishing

pom.xml
=> fix(api): Avoid duplicate name for groups and endpoints

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/EndpointNameInvalidException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateTest.java
=> fix(endpoints): resolve endpoints with special characters in their name

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PortalConfigEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/parameters/Key.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
This closes gravitee-io/issues#1947
=> feat: Allow to audit the people who consult the log detail

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UsersRegisterResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UsersResource.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/UserService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/common/JWTHelper.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notification/PortalHook.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/UserServiceTest.java
This closes gravitee-io/issues#1505
=> feat: User creation from management gui / management API

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateWithDefinitionTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateWithDefinitionTest.java
This closes gravitee-io/issues#1883
=> fix: Error while importing an API

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(prometheus): add default configuration

gravitee-management-api-model/src/main/java/io/gravitee/management/model/documentation/PageQuery.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/searcher/ApiDocumentSearcher.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/upgrade/SearchIndexUpgrader.java
=> feat(search): improve the search engine

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PortalConfigEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequest.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequestItem.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApplicationRequest.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApplicationRequestItem.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/parameters/Key.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
This closes gravitee-io/issues#1948
=> feat: Audit on API user from JWT

gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/authentication/LdapAuthenticationProvider.java, gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/authentication/UserDetailsContextPropertiesMapper.java, gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapContextSourceFactory.java, gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java, gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/utils/LdapUtils.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(ldap): add new configuration to search for users

gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/EmailNotifierServiceTest.java
=> fix(email):  Email template not found for hook SUBSCRIPTION_REJECTED

gravitee-management-api-model/src/main/java/io/gravitee/management/model/EventQuery.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/InstanceService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EventServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/HealthCheckServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InstanceServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
This closes gravitee-io/issues#2067
=> feat: Optimizing event recuperation

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPagesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalPagesResource.java
This closes gravitee-io/issues#2001
=> feat: Add a button to fetch API/portal docs

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiLogsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationLogsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/LogsService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
This closes gravitee-io/issues#2004
=> feat: Allows to export logs in a CSV file

gravitee-management-api-idp/gravitee-management-api-idp-repository/src/main/java/io/gravitee/management/idp/repository/lookup/RepositoryIdentityLookup.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateUserEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UserEntity.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/UserRepositoryProxy.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/UserService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/upgrade/DefaultUserStatusUpgrader.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, pom.xml
=> feat(user): archive users

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiAuditResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AuditResource.java, pom.xml
=> fix(audit): add missing events

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPageResource.java
This closes [gravitee-io/issues/issues/2108](https://github.com/gravitee-io/issues/issues/2108)
=> bug - NPE in ApiPage when not authenticated

gravitee-management-api-model/src/main/java/io/gravitee/management/model/analytics/query/LogQuery.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiAnalyticsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiLogsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationAnalyticsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationLogsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformAnalyticsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/LogsParam.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java, pom.xml
This closes gravitee-io/issues#2003
=> feat: Allows to sort the logs by date, path, status

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
This closes gravitee-io/issues#2131
=> fix: Registration not available when not logged in

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/oauth2/AuthorizationServerConfigurationParser.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/oauth2/UserMapping.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(idp): oauth idp could authorize users without email

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/notifications/portal/PORTAL.PASSWORD_RESET.yml, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/notifications/portal/PORTAL.USER_FIRST_LOGIN.yml
fixes https://github.com/gravitee-io/issues/issues/2132
- replace user.username with user.displayName
=> Fix "Portal notification of new user is missing user.username"

gravitee-management-api-service/src/main/java/io/gravitee/management/service/builder/EmailNotificationBuilder.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/userCreated.html
=> fix(notification): missing notification when a user is created

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/UpdateApiEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ApiPermission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, pom.xml
=> feat(api): Define response templates to override policy response

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PortalConfigEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/parameters/Key.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java
closes gravitee-io/issues#2103
=> feat(audit): add API Logging configuration audit logs

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/identity/SocialIdentityProviderImpl.java
if there is any in identity provider configuration
=> Provide userLogoutEndpoint for frontend

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/upgrade/IdentityProviderUpgrader.java
=> feat(idp): allow configuration with gravitee.yml

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewTagEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/TagEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateTagEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/CurrentUserResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GroupResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/TagsResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/GroupService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/TagNotAllowedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/TagNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AbstractService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TagServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateWithDefinitionTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateWithDefinitionTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_Update_DefaultLoggingMaxDurationTest.java
This closes gravitee-io/issues#1995
=> feat: Allows to define permission to publish on a sharding tag

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/LogsParam.java, pom.xml
This closes gravitee-io/issues#2053
=> feat: Allows to search in logs payloads

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalPagesResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PageService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
This closes gravitee-io/issues#2171
=> fix: Attributes not interpreted anymore on api pages

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TagServiceImpl.java
=> fix(tags): NPE if tag has no restricted groups

gravitee-management-api-model/src/main/java/io/gravitee/management/model/command/CommandEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/command/CommandQuery.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/command/CommandSearchIndexerEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/command/CommandTags.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/command/NewCommandEntity.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/CommandRepositoryProxy.java, gravitee-management-api-service/pom.xml, gravitee-management-api-service/src/main/java/io/gravitee/management/service/CommandService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/Message2RecipientNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/CommandServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MessageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/SearchEngineServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/upgrade/SearchIndexUpgrader.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/search/SearchEngineService.java, gravitee-management-api-services/gravitee-management-api-services-search-indexer/pom.xml, gravitee-management-api-services/gravitee-management-api-services-search-indexer/src/main/assembly/plugin-assembly.xml, gravitee-management-api-services/gravitee-management-api-services-search-indexer/src/main/java/io/gravitee/management/services/search/ScheduledSearchIndexerService.java, gravitee-management-api-services/gravitee-management-api-services-search-indexer/src/main/java/io/gravitee/management/services/search/spring/SearchIndexerConfiguration.java, gravitee-management-api-services/gravitee-management-api-services-search-indexer/src/main/resources/plugin.properties, gravitee-management-api-services/gravitee-management-api-services-search-indexer/src/test/java/io/gravitee/management/services/search/ScheduledSearchIndexerServiceTest.java, gravitee-management-api-services/pom.xml, pom.xml
=> feat(search): synchronize search indexes across management instances

gravitee-management-api-security/src/main/java/io/gravitee/management/security/authentication/GraviteeAuthenticationDetails.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/authentication/GraviteeAuthenticationDetailsSource.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/listener/AuthenticationFailureListener.java, gravitee-management-api-security/src/test/java/io/gravitee/management/security/authentication/GraviteeAuthenticationDetailsTest.java
this closes gravitee-io/issues#2117
=> Add Rest API trace for Authentication failure Event

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiMediaResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/CurrentUserResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalMediaResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ViewResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/JerseySpringTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/ApiResourceTest.java, gravitee-management-api-rest/src/test/resources/media/hacked1.svg, gravitee-management-api-rest/src/test/resources/media/hacked2.svg, gravitee-management-api-rest/src/test/resources/media/hacked3.svg, gravitee-management-api-rest/src/test/resources/media/hacked4.svg, gravitee-management-api-rest/src/test/resources/media/logo.svg, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/UploadUnauthorized.java
This closes gravitee-io/issues#2236
=> fix: CVE 623

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AuditServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/NotifierServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/SearchEngineServiceImpl.java
=> chore(): circular dependency error on startup

gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/JWTAuthenticationFilter.java
=> feat(auth): do not log expired token in error

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
=> fix(logs): do not checked 'endpoint' if no endpoint is called

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPageResource.java
Closes gravitee-io/issues#2264
=> fix(page): Apply template to API's pages.

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ViewResource.java
=> fix(views): unable to display views picture if not admin

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PlanEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlansResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TaskServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiKeyServiceTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanService_CloseTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanService_DeleteTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanService_DepreciateTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanService_PublishTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportMultipleEndpointGroups-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithouGroup.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition+plans.json, pom.xml
Closes gravitee-io/issues#2283
=> feat(plan): plan is now linked to one and only one api"

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PortalConfigEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/parameters/Key.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java
This closes gravitee-io/issues#1997
=> feat: Multi analytics dashboards

gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/Api1_20VersionSerializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiCompositeSerializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiSerializer.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_20.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers-1_20.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_20.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans-1_20.json
=> fix(export): make api export compatible with 1.20

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(apis): search by context-path doesn't work for non admin users

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/SwaggerVerb.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_PrepareTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/mock/enum-example.yml
This closes gravitee-io/issues#2291
=> fix: better support of swagger mock generation

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewPlanEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/PlanEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdatePlanEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, pom.xml
Closes gravitee-io/issues#2219
--wip-- [skip ci]
=> feat(plan): Manage plan deployment using sharding tags

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/filter/GraviteeContextFilter.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AlertsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AuditResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ConfigurationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/CurrentUserResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/EnvironmentResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/FetchersResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/InstancesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/MessagesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformTicketsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PoliciesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalEntryPointsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ResourcesResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ServicesDiscoveryResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/SubscriptionsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UsersResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/search/SearchResource.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/JerseySpringTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/CurrentUserResourceTest.java, gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/common/GraviteeContext.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EnvironmentServiceImpl.java, gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/jetty/JettyEmbeddedContainer.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
Closes gravitee-io/issues#2287
=> feat(env): call API with DEFAULT env

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ParameterServiceImpl.java
=> feat(parameters): save parameters onlyf if value changes

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java
=> feat(auth): add debug logs on the authent process

gravitee-management-api-model/src/main/java/io/gravitee/management/model/application/OAuthClientSettings.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/configuration/application/registration/ClientRegistrationProviderEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/configuration/application/registration/NewClientRegistrationProviderEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/configuration/application/registration/UpdateClientRegistrationProviderEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApplicationService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/configuration/application/ClientRegistrationService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApplicationRenewClientSecretException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/application/registration/ClientRegistrationServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/application/registration/InvalidRenewClientSecretException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/application/registration/client/DiscoveryBasedDynamicClientRegistrationProviderClient.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/application/registration/client/DynamicClientRegistrationProviderClient.java
Closes gravitee-io/issues#2350
=> feat(application): Add renew client_secret support

gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiDefaultSerializer.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition.json
=> fix(): export response templates

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java
=> fix: API can not be started without being reviewed

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/UpdateApiEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix: Lifecycle state is required when updating an API

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_PrepareTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/mock/callback-example.yaml
=> fix(import): generate mock for simple properties

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiHealthResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/healthcheck/LogsParam.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/HealthCheckServiceImpl.java, pom.xml
closes gravitee-io/issues#2378
=> feat(healthcheck): adding a time filter in the healthcheck screen

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/bin/gravitee
=> fix(bin) add GRAVITEE_OPTS to the command line

gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/DynamicPropertyUpdater.java
=> fix(dynamic-properties): authenticate the service as admin 

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/SwaggerVerb.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_PrepareTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/mock/json-api.yml
=> fix(mock openapi): improve the coverage of this feature

gravitee-management-api-service/src/main/java/io/gravitee/management/service/ParameterService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ParameterServiceImpl.java
=> fix: Error while importing an API when no default entrypoint is defined

gravitee-management-api-standalone/gravitee-management-api-standalone-container/pom.xml, pom.xml
=> chore(): provide the resource-oauth2-provider-api lib

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanService_CloseTest.java
=> fix(plan): close paused subscriptions when closing plan

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewApplicationEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/NewApiEntity.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/ApisResourceTest.java, gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/ApplicationsResourceTest.java
Closes gravitee-io/issues#2466
=> fix(application): Application's name must contain at least 4 characters

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanService_CloseTest.java
=> feat(subscriptions): allow apps to close all subscriptions

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/UserServiceTest.java
=> fix(user): Anonymize user sourceId on deletion

README.adoc
=> chore(README): update documentation

gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/Api1_15VersionSerializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/Api1_25VersionSerializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiCompositeSerializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiSerializer.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/PlanEntityBefore_3_00.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_25.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportMultipleEndpointGroups-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers-1_25.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_25.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans-1_25.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition+plans.json
since a Plan is linked to one api instead of many
Fixes gravitee-io/issues#2540
=> fix(jsonExport): fixes JsonExport for 1.15 and 1.20 and creates 1.25

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/SubscriptionService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java
=> feat: Allows to export subscriptions to CSV

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java
=> feat(logs) add header on logs export

pom.xml
=> fix: Jetty server becomes unresponsive after being idle

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/RatingServiceImpl.java
=> fix: Ratings do not display users 'in memory'

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/PlanRestrictedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java
=> fix: I can subscribe to a plan for which I do not have access

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java
=> fix(): change SSL protocol

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApiKeyAlreadyExpiredException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiKeyServiceTest.java
=> fix: Avoid some actions on expired api keys

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/UserServiceTest.java
=> fix(user): anonymize all user data on delete

gravitee-management-api-idp/gravitee-management-api-idp-api/src/main/java/io/gravitee/management/idp/api/identity/IdentityLookup.java, gravitee-management-api-idp/gravitee-management-api-idp-api/src/main/java/io/gravitee/management/idp/api/identity/SearchableUser.java, gravitee-management-api-idp/gravitee-management-api-idp-core/src/main/java/io/gravitee/management/idp/core/authentication/impl/CompositeIdentityManager.java, gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java, gravitee-management-api-idp/gravitee-management-api-idp-repository/src/main/java/io/gravitee/management/idp/repository/lookup/RepositoryIdentityLookup.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateWithDefinitionTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(user): add an option to retreive users email in search dialog boxes

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/configuration/dictionary/DictionaryResource.java
=> fix(dictionary): readonly users must not see the provider informations

gravitee-rest-api-management/gravitee-rest-api-management-security/src/main/java/io/gravitee/rest/api/management/security/config/BasicSecurityConfigurerAdapter.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationLogsResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AuthResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/EnvironmentResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/auth/AbstractAuthenticationResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/auth/OAuth2AuthenticationResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/param/AnalyticsParam.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/PlanMapperTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/params/AnalyticsParamTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/AbstractResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResourceNotAuthenticatedTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceNotAuthenticatedTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationNotificationSettingsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/AuthResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/auth/OAuth2AuthenticationResourceTest.java
Closes gravitee-io/issues#2585
=> feat(env): implement /auth

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/EntrypointsResource.java
=> fix: Users with read right on Entrypoints cannot list

gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/Api1_15VersionSerializer.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_20.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportMultipleEndpointGroups-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithouGroup.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers-1_20.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_20.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans-1_15.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans-1_20.json, gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans.json, pom.xml
=> fix(requests): do not encode/decode query parameters by default

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java
=> fix(user): hide archived apps

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/enhancer/ViewEnhancer.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ViewMapper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AbstractResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/EnvironmentResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ViewResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ViewsResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/auth/AbstractAuthenticationResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/spring/RestPortalConfiguration.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/utils/PortalApiLinkHelper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/enhancer/ViewEnhancerTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ViewMapperTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/AbstractResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ViewResourceNotAuthenticatedTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ViewResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ViewsResourceNotAuthenticatedTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ViewsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/utils/PortalApiLinkHelperTest.java, gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ViewServiceImpl.java
Closes gravitee-io/issues#2586
=> feat(multi-env): add /views

gravitee-management-api-idp/gravitee-management-api-idp-ldap/pom.xml, gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/authentication/UserDetailsContextPropertiesMapper.java, gravitee-management-api-rest/pom.xml, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/spring/EmailConfiguration.java
=> fix: ExceptionInInitializerError while upgrading jdk to 11

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(api): verify regex before saving the api

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(api): verify regex paths before saving the api

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationNotificationSettingsResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UserResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationNotificationSettingsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java, gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/identity/SocialIdentityProviderImpl.java, postman/README.adoc, postman/collections/graviteeio-apim-portal-authorizations-collection.json, postman/environment/dev.json
+ one bug fix
Closes gravitee-io/issues#2664
=> feat(v3): add postman collection to test authorizations

gravitee-management-api-services/gravitee-management-api-services-dictionary/src/main/java/io/gravitee/management/services/dictionary/DictionaryService.java, gravitee-management-api-services/gravitee-management-api-services-sync/src/main/java/io/gravitee/management/services/sync/SyncManager.java
Closes gravitee-io/issues#2663
=> fix(dictionaries): Do not try to find a deleted dictionary

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java
=> fix(application): do not throw exceptions if there's no application PO

gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/GenericNotificationConfigRepositoryProxy.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/PortalNotificationConfigRepositoryProxy.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/GenericNotificationConfigService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PortalNotificationConfigService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GenericNotificationConfigServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PortalNotificationConfigServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/UserServiceTest.java, pom.xml
=> fix(user): remove user notif on delete user

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UserResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/utils/PortalApiLinkHelper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/UserMapperTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UserResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/utils/PortalApiLinkHelperTest.java
Closes gravitee-io/issues#2683
=> feat(v3): add user links

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/provider/AbstractExceptionMapper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AbstractResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingsResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationMembersResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ViewResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/auth/OAuth2AuthenticationResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPageResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPagesResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResourceNotAuthenticatedTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceNotAuthenticatedTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationLogsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationMembersResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PageResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PagesResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UserNotificationsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UsersResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ViewResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ViewsResourceNotAuthenticatedTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ViewsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java
Closes gravitee-io/issues#2588
=> feat(v3): improve documentation

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AbstractResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationAnalyticsResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPagesResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResourceNotAuthenticatedTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceNotAuthenticatedTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationLogsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationMembersResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PagesResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UserNotificationsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UsersResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ViewsResourceNotAuthenticatedTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ViewsResourceTest.java
Closes gravitee-io/issues#2616
=> feat(v3): improve openapi by removing inheritance and dataType

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PortalConfigEntity.java, gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/am/AMIdentityProviderEntity.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/pom.xml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/IdentityProviderMapper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/EnvironmentResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/InfoResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/api.properties, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapperTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/IdentityProviderMapperTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/AbstractResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationIdentitiesResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/InfoResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/api.properties, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/expectedPortalConfiguration.json, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/portalConfigEntity.json
Closes gravitee-io/issues#2718
=> feat(v3): add /configuration and /info

pom.xml
=> chore(): add java11 compatibility

gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/plugins/RepositoryPluginHandler.java
Closes gravitee-io/issues#2693
=> fix(repository): Try to connect to the repository indefinitely

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewApplicationEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/NewApiEntity.java
=> fix(api/app): allow name with one letter

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/DuplicateApiEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PageService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/PlanService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java
=> feat: Duplicate an api to create a new version of the API

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiMetadataServiceImpl.java
Closes gravitee-io/issues#2703
=> fix: Delete button is not displayed on metadata sometimes

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/SwaggerVerb.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_PrepareTest.java
Closes gravitee-io/issues#2766
=> fix: Take care of content type on swagger/OAI specs

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java
Closes gravitee-io/issues#2625
=> feat(api): Report unknown API request calls (api not found)

gravitee-management-api-model/src/main/java/io/gravitee/management/model/DashboardEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/DashboardReferenceType.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewDashboardEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateDashboardEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ManagementPermission.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java, gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/DashboardRepositoryProxy.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ConfigurationResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/DashboardsResource.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformAnalyticsResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/DashboardService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/DashboardNotFoundException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/DashboardServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/upgrade/DefaultDashboardsUpgrader.java, gravitee-management-api-service/src/main/resources/dashboards/api_device.json, gravitee-management-api-service/src/main/resources/dashboards/api_geo.json, gravitee-management-api-service/src/main/resources/dashboards/api_global.json, gravitee-management-api-service/src/main/resources/dashboards/application_device.json, gravitee-management-api-service/src/main/resources/dashboards/application_geo.json, gravitee-management-api-service/src/main/resources/dashboards/application_global.json, gravitee-management-api-service/src/main/resources/dashboards/platform_device.json, gravitee-management-api-service/src/main/resources/dashboards/platform_geo.json, gravitee-management-api-service/src/main/resources/dashboards/platform_global.json, gravitee-management-api-service/src/test/java/io/gravitee/management/service/DashboardServiceTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/RoleService_CreateOrUpdateSystemRolesTest.java, pom.xml
Closes gravitee-io/issues#2595
=> feat: Dynamic global dashboards of analytics

gravitee-management-api-idp/gravitee-management-api-idp-api/src/main/java/io/gravitee/management/idp/api/authentication/UserDetails.java, gravitee-management-api-idp/gravitee-management-api-idp-memory/src/main/java/io/gravitee/management/idp/memory/authentication/InMemoryAuthentificationProvider.java, gravitee-management-api-idp/gravitee-management-api-idp-memory/src/main/java/io/gravitee/management/idp/memory/authentication/spring/InMemoryAuthenticationProviderConfiguration.java, gravitee-management-api-idp/gravitee-management-api-idp-memory/src/main/java/io/gravitee/management/idp/memory/authentication/spring/InMemoryGraviteeUserDetailsManager.java, gravitee-management-api-idp/gravitee-management-api-idp-memory/src/main/java/io/gravitee/management/idp/memory/lookup/InMemoryIdentityLookup.java, gravitee-management-api-idp/gravitee-management-api-idp-memory/src/main/java/io/gravitee/management/idp/memory/lookup/spring/InMemoryLookupConfiguration.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat(user): add email on inmemory users

gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApplicationEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/UpdateApiEntity.java
=> feat(api/app): allow names with 512 char

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/upgrade/DefaultDashboardsUpgrader.java, gravitee-management-api-service/src/main/resources/dashboards/api_user.json, gravitee-management-api-service/src/main/resources/dashboards/application_user.json, gravitee-management-api-service/src/main/resources/dashboards/platform_user.json
=> feat: Change device dashboard to a user oriented dashboard

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/InfoResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UsersResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/UserMapperTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UserResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UsersResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java, gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/UserService.java, gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/UserRegistrationUnavailableException.java, gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java, postman/collections/graviteeio-apim-portal-authorizations-collection.json, postman/collections/graviteeio-apim-portal-errors-collection.json
Closes gravitee-io/issues#2828
=> feat(portal): add registration resources to portal API

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java
Closes gravitee-io/issues#2815
=> fix(analytics): Add a deleted xxxx in case of no more valid data

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateWithDefinitionTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/EmailNotifierServiceTest.java
=> feat(mail): support freemarker into email recipients

gravitee-management-api-service/src/main/java/io/gravitee/management/service/builder/EmailNotificationBuilder.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApiDeprecatedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notification/ApiHook.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiDeprecated.html, gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/notifications/portal/API.API_DEPRECATED.yml
=> feat: Lifecycle - allows to deprecate an API

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/HttpClientServiceImpl.java
Closes gravitee-io/issues#2727
=> fix(http): Content-length is based on the size of the bytes array

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApplicationArchivedException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java
=> fix(application): Archived applications must be in readonly mode

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiModelEntity.java, gravitee-management-api-model/src/main/java/io/gravitee/management/model/ProxyModelEntity.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
=> fix(doc): preserve the legacy 'api.proxy.contextPath' attribute

.gitignore, gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/spring/StandaloneConfiguration.java
Closes gravitee-io/issues#2878
=> feat(node): Use node factory instead of node implementation

pom.xml
=> fix(audits): add api events

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
Closes gravitee-io/issues#2892
=> refactor: rename API tag to Api for better client generation

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/UserMapperTest.java
Closes gravitee-io/issues#2870
=> feat(portal): change display name for the user-menu in the new portal

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_DeleteTest.java
=> fix: When deleting an API, its pages should be also deleted

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ViewsResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ViewsResourceTest.java
=> fix: Do not return view ALL when requesting views

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/AnalyticsParam.java
Closes gravitee-io/issues#2914
=> fix(swagger): Add documentation for analytics API

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
=> fix: View all is not well handled

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/param/ApisParam.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceTest.java
=> feat: Allows to get apis by excluding a category

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
Closes gravitee-io/issues#2924
=> fix: add apiCategoryExcludedQueryParam to list of /apis params

gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewGroupEntity.java, gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GroupResource.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/GroupService.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java
Closes gravitee-io/issues#2253
=> fix(group): A group can be associated to existing APIs and or Apps

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ViewServiceImpl.java
Closes gravitee-io/issues#2909
=> fix(view): Do not update view's picture when re-ordering

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AbstractResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationLogsResourceTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PaginationFilteringTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PaginationLinkTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java
Closes gravitee-io/issues#2793
=> feat(portal): implement /apis/_search resource

gravitee-management-api-services/gravitee-management-api-services-dictionary/src/main/java/io/gravitee/management/services/dictionary/DictionaryService.java, gravitee-management-api-services/gravitee-management-api-services-dictionary/src/main/java/io/gravitee/management/services/dictionary/provider/http/HttpProvider.java, gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/DynamicPropertiesService.java, gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/main/java/io/gravitee/management/services/dynamicproperties/provider/http/HttpProvider.java, gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/src/test/java/io/gravitee/management/services/dynamicproperties/provider/http/HttpProviderTest.java, gravitee-management-api-standalone/gravitee-management-api-standalone-container/pom.xml, pom.xml
=> feat(services): Add a user-agent header for all services requests

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApplicationMapper.java, gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java
=> feat: Allow a user to contact owner of the platform

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapperTest.java
=> fix(api): hide hidden views in ApiResource

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AbstractResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceTest.java
=> feat: allow to get all entities on paginated resources

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UserResource.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/UserMapperTest.java, gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UserResourceTest.java
Closes gravitee-io/issues#2950
=> fix: Avatar not updated correctly due to browser cache

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
Closes gravitee-io/issues#2945
=> fix: Do not log error if primary owner has no email

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/EndpointMissingException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/HealthcheckInheritanceException.java, gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateTest.java, gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_Update_DefaultLoggingMaxDurationTest.java, pom.xml
=> fix(api): add controls on api creation and update

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResourceTest.java, gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/SubscriptionInvalidException.java
=> fix: change SubscriptionException error message

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
Closes gravitee-io/issues#2882
=> feat: hide categories link in the menu when "enable view mode" is false

pom.xml
Closes gravitee-io/issues#2963
=> chore: Update node dependency
