pom.xml

fix(prometheus): register HC service only on Prometheus

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiMetricsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/AbstractResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiMetricsResourceTest.java

Closes gravitee-io/issues#2960

feat(portal): implements /apis/{apidId}/metrics

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java

fix(oauth): log user mapping error in warning

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/quality/QualityRulesResource.java

fix(quality-rules): do not require read access to get all quality rules

---

gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/jetty/JettyConfiguration.java
gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/jetty/JettyServerFactory.java
gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#2978

feat(http): Add support for PKCS12 for HTTP server

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java

fix(analytics): replace '1' to '?' in analytics response

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/PageMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPageResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPagesResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/PageResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/PagesResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/utils/PortalApiLinkHelper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/PageMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPageResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPagesResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PageResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PagesResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/utils/PortalApiLinkHelperTest.java

and implement /apis/{apiId}/pages/{pageId}/content & /pages/{pageId}/content
Closes gravitee-io/issues#2796

feat(portal): add _links in /pages and /apis/{apiId}/pages responses

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiSubscribersResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiSubscribersResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java

Closes gravitee-io/issues#2789

feat(portal): add information about an API

---

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#2590

doc: Add doc on how to add email on a user inmemory

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_StartTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_StopTest.java

fix(email): do not send email if no recipient

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/PageMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/PageMapperTest.java

Closes gravitee-io/issues#3039

feat(portal): add the possibility to choose openapi documentation viewer

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapperTest.java

fix(portal): do not return views if viewMode is disabled

---

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/bin/gravitee.bat

fix(gravitee.bat): wrong comment syntax

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/SocialIdentityProviderEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/am/AMIdentityProviderEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/github/GitHubIdentityProviderEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/google/GoogleIdentityProviderEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/oidc/OIDCIdentityProviderEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/provider/PayloadInputBodyReader.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/GraviteePortalApplication.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/auth/AbstractAuthenticationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/auth/OAuth2AuthenticationResourceTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
pom.xml

Closes gravitee-io/issues#2838

feat: Integration of login with OAuth2 providers

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/MetadataService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiMetadataServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MetadataServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TicketServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateWithDefinitionTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/MetadataServiceTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/TicketServiceTest.java

closes gravitee-io/issues#3049

feat(metadata): add EL support for the "email-support" API metadata

---

gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/MembershipRepositoryProxy.java
gravitee-management-api-repository/src/main/java/io/gravitee/management/repository/proxy/PortalNotificationConfigRepositoryProxy.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/GenericNotificationConfigService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/MembershipService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/PortalNotificationConfigService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GenericNotificationConfigServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PortalNotificationConfigServiceImpl.java
pom.xml

fix(api): delete memberships and notifications on delete

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/subscription/SubscriptionQuery.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApplicationMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/KeyMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiSubscribersResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/KeyMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResourceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/SubscriptionServiceTest.java

fix(subscription): cannot add null value in subscription query 

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPageResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPagesResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalPagesResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/JerseySpringTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiPagesResourceAdminTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/PortalPagesResourceAdminTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/SystemFolderType.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPagesResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/PagesResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PagesResourceTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PageActionException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PageSystemFolderActionException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/DocumentationSystemFolderUpgrader.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_CreateWithDefinitionTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_UpdateTest.java

Closes gravitee-io/issues#3048

feat(portal): Add new kinds of 'Page'

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResourceTest.java

feat(applications): add forSubscription query param for filtering

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/spring/ServiceConfiguration.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateWithDefinitionTest.java
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition_enum_lowercase.json

Closes gravitee-io/issues#2995

fix(management): the enums not case-insensitive when an api is imported

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/LogsParam.java

fix(logs): escape reserved words during research

---

gravitee-management-api-security/src/main/java/io/gravitee/management/security/listener/AuthenticationSuccessListener.java

Closes gravitee-io/issues#3103

fix: The configuration of an email on a user (in memory) does not work

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/MetadataServiceTest.java

Closes gravitee-io/issues#3104

fix: Error trying to import API with primary owner without email

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java

Closes gravitee-io/issues#3136

fix: Admin should not get all the APIs

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PortalConfigEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/parameters/Key.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/filter/MaintenanceFilter.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/GraviteeApplication.java
gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/MaintenanceModeException.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java

feat(maintenance): add a maintenance mode for the ui and api

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/pom.xml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/RatingMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AbstractResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswerResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswersResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/EnvironmentResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/PermissionsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UserResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ViewResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/security/Permission.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswerResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswersResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingsResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PermissionsResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PictureManagementTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/RatingService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/RatingAnswerNotFoundException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/RatingServiceImpl.java

feat(portal): add resources for rating an api

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java

fix(subscription): update subscription ending date

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java

fix(apikey): expire date cannot ended after subscription

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiSerializer.java

fix(management) API documentation import preserves folders structure

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PortalPagesResource.java

fix(pages) allow non admin to administrate portal pages

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/IdentityProviderMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UserResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/UserMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UserResourceTest.java

Closes gravitee-io/issues#2806

feat: Allow a user to subscribe to notifications

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java

fix: Avatar is lost after navigation

---

gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java

fix(portal): fix basic security

---

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#3221

fix(config): Bad defautl value for HTTP proxy

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java

Closes gravitee-io/issues#3171

fix(group): Reverse newly created entity and mapped entity

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/TokenEntity.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/AbstractAuthenticationResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java

Closes gravitee-io/issues#3231

fix(oauth): Add a state while doing oauth authentication

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PermissionServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/MembershipService_GetMemberPermissionsTest.java

Closes gravitee-io/issues#3238

fix(permission): Group permissions are merged with user permissions

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java

Closes gravitee-io/issues#3228

fix: Cors request considered as "Deleted Application"

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformAnalyticsResource.java

Closes gravitee-io/issues#3226

fix: Log unknown path for unknown APIs

---

gravitee-management-api-standalone/gravitee-management-api-standalone-container/pom.xml
gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/ManagementContainer.java

Closes gravitee-io/issues#3229

fix(container): Move JUL logs to SLF4j

---

gravitee-management-api-idp/gravitee-management-api-idp-memory/src/main/java/io/gravitee/management/idp/memory/authentication/InMemoryAuthentificationProvider.java
gravitee-management-api-idp/gravitee-management-api-idp-memory/src/main/java/io/gravitee/management/idp/memory/authentication/spring/InMemoryGraviteeUserDetailsManager.java
gravitee-management-api-idp/gravitee-management-api-idp-memory/src/main/java/io/gravitee/management/idp/memory/lookup/InMemoryIdentityLookup.java
gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

closes gravitee-io/issues#3234

feat(idp): add firstname and lastname support for inmemory users

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/UserEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/UserMembership.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/UsersResource.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java

Closes gravitee-io/issues#2425

feat(user): Add a flag to indicate that the user is PO

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApplicationMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationSubscribersResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UserResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ApplicationMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/UserMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java

Closes gravitee-io/issues#2799

feat: Allow a user to consult/edit global settings of an application

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/TopApisResource.java

Closes gravitee-io/issues#3248

fix: Picture links should take care of organization

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/swagger/transformer/entrypoints/EntrypointsSwaggerV2Transformer.java

Closes gravitee-io/issues#3259

fix: fail to parse Swagger page with dynamic freemarker values

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/ApiRequest.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/log/PlatformRequestItem.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformLogsResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformResource.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/LogsService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java

Closes gravitee-io/issues#3233

feat(logs): Provide a way to consult API logs from platform dashboard

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_FindByUserTest.java

Closes gravitee-io/issues#3295

fix: A user should be able to see its subscribed APIs

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ThemeServiceTest.java

feat: add gv-autocomplete to theme definition

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApplicationService_ArchiveTest.java

Closes gravitee-io/issues#3273

fix: Some users are wrongly flagged as primary owners

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java

fix(application): do not log in error a missing PO on a archived app

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java

fix(portal): add authorizations on /theme/** for anonymous users

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswerResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswersResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/PermissionsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswerResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswersResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingResourceTest.java

feat(portal): add all permissions for admin on API/APP

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_Update_DefaultLoggingMaxDurationTest.java

Closes gravitee-io/issues#3282

fix: Manual unlocking of detailed logging limitation

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java

Closes gravitee-io/issues#3267

fix: Use the correct log lever for errors on token exchange

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/swagger/SwaggerProperties.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/swagger/transformer/entrypoints/EntrypointsOAITransformer.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/swagger/transformer/entrypoints/EntrypointsSwaggerV2Transformer.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/swagger/transformer/page/AbstractPageConfigurationSwaggerTransformer.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/swagger/transformer/page/PageConfigurationOAITransformer.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/swagger/transformer/page/PageConfigurationSwaggerV2Transformer.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_TransformTest.java

Closes gravitee-io/issues#3277

feat(swagger): Servers in descriptor are based on API entrypoints

---

gravitee-management-api-model/pom.xml
gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/ImportSwaggerDescriptorEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/PrimaryOwnerEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiListItem.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/NewApiEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/UpdateApiEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/application/ApplicationListItem.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiAuditResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiKeysResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiMetadataResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiRatingResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/EntrypointsResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/RoleScopeResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/TagsResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/AnalyticsParam.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/ApisParam.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/AuditParam.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/LogsParam.java
gravitee-management-api-service/pom.xml
pom.xml

fix(): improve the rest-api swagger documentation

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/UpdateApiEntity.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java
gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiSerializer.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateWithDefinitionTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_ExportAsJsonTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateWithDefinitionTest.java
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_20.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportMultipleEndpointGroups-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers-1_20.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMetadata-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMetadata-1_20.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMetadata.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_20.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans-1_20.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition+metadata.json

fix(api): export API metadata

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/application/registration/ClientRegistrationServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/application/registration/client/DynamicClientRegistrationProviderClient.java

Closes gravitee-io/issues#3180

fix(application): Set the client_id when updating a DCR application

---

gravitee-management-api-services/gravitee-management-api-services-dictionary/src/main/java/io/gravitee/management/services/dictionary/DictionaryService.java
gravitee-management-api-services/gravitee-management-api-services-dictionary/src/main/java/io/gravitee/management/services/dictionary/provider/http/HttpProvider.java
gravitee-management-api-services/gravitee-management-api-services-dictionary/src/main/java/io/gravitee/management/services/dictionary/provider/http/configuration/HttpHeader.java

Closes gravitee-io/issues#3296

feat(dictionary): Provide support HTTP headers

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UsersResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UsersResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/UserService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/UserNotActiveException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/UserNotFoundForPasswordResetException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/UserServiceTest.java

Closes gravitee-io/issues#2822

feat(portal): allow a user to reset his password

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PortalConfigEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UserResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UserResourceTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/PermissionService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PermissionServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PermissionServiceTest.java

Closes gravitee-io/issues#3109

feat(portal) : add management link in portal usermenu

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiEntity.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java

Closes gravitee-io/issues#3356

fix(api): Add default context-path to API entity

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java

Closes gravitee-io/issues#3349

fix(logs): Manage unknown API

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationAnalyticsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/AnalyticsMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/DashboardMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationAnalyticsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/DashboardsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/EnvironmentsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/AnalyticsCalculateException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AnalyticsServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/HealthCheckServiceImpl.java

Closes gravitee-io/issues#2804

feat: Allow a user to consult analytics of an application

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java

Closes gravitee-io/issues#3193

feat(management): remove legacy portal

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CurrentUserResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/UserResource.java

fix(avatar): empty response if user has no avatar

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/alert/AlertEventEntity.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java

Closes gravitee-io/issues#3362

fix(subscription): Api-key without expiration date are well managed

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewApplicationEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/application/ApplicationGrantTypeEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/application/ApplicationTypeEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/application/ApplicationTypesEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/RatingMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswersResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/RatingMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/AbstractResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswersResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingsResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/expectedPortalConfiguration.json
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/configuration/application/ApplicationTypeService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/application/ApplicationTypeServiceImpl.java
gravitee-rest-api-service/src/main/resources/applications/types.json
gravitee-rest-api-service/src/main/resources/themes/default/definition.json
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationTypeServiceTest.java

feat: Allow a user to create an application

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/KeyMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/SubscriptionMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AbstractResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml

Closes gravitee-io/issues#3114

feat: Allow a user to consult subscriptions of an application

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/LogMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AbstractResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationLogsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationSubscribersResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml

Closes gravitee-io/issues#2805

feat: Allow a user to consult logs of an application

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ThemeServiceTest.java

feat: upgrade definition of theme

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java

Closes gravitee-io/issues#3398

fix: Support email message is displaying html elements

---

gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/ManagementContainer.java

Closes gravitee-io/issues#3360

fix(logging): Plug Java Util Logging (JUL) to SLF4J

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiMetadataServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateWithDefinitionTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateWithDefinitionTest.java

Closes gravitee-io/issues#3409

fix: Metadata are not well imported while creating or updating an API

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java

Closes gravitee-io/issues#3404

fix: Entrypoints are incorrect in case of virtual hosting configuration

---

gravitee-management-api-service/src/main/resources/dashboards/application_global.json

fix: Error on top path column name

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/AbstractViewResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ViewResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ViewServiceImpl.java

Closes gravitee-io/issues#3178

feat(portal): display Views picture

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json

feat(portal): upgrade colors of gv-tree in default theme

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PortalConfigEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/expectedPortalConfiguration.json
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/portalConfigEntity.json

Closes gravitee-io/issues#3439

feat(portal): remove dev mode

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json

feat: upgrade theme for gv-tree component

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiKeyServiceTest.java

fix(apikey): save paused subscriptions

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java

fix(swagger): keep the swagger config on api update from swagger

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/PortalNotificationMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UserNotificationsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UserNotificationsResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/expectedPortalConfiguration.json
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PortalNotificationServiceImpl.java
gravitee-rest-api-service/src/main/resources/themes/default/definition.json
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ThemeServiceTest.java

feat: Add browsers notifications

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json

fix gravitee-io/issues#3467
fix gravitee-io/issues#3453

fix: resolve category image position

---

gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExport-1_15.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExport-1_20.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExport-1_25.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExport.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportMultipleEndpointGroups-1_15.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithouGroup.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMembers-1_15.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMembers-1_20.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMembers-1_25.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMembers.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPages-1_15.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPages-1_20.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPages-1_25.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPages.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPlans-1_15.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPlans-1_20.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPlans-1_25.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPlans.json
pom.xml

Closes gravitee-io/issues#2634

feat(gateway): remove encodeURI

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json

feat: upgrade theme for gv-card & gv-header components

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/MembershipService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PermissionServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_ExportAsJsonTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_FindByIdTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationService_FindByUserTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/MembershipService_GetMemberPermissionsTest.java
gravitee-rest-api-services/gravitee-rest-api-services-sync/src/main/java/io/gravitee/rest/api/services/sync/SyncManager.java

fix(portal): Improve roles and permissions when user is in a group

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/RoleServiceImpl.java

fix(management): fix role updating

---

gravitee-rest-api-idp/gravitee-rest-api-idp-api/src/main/java/io/gravitee/rest/api/idp/api/authentication/UserDetails.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CurrentUserResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateUserEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UserEntity.java
gravitee-rest-api-security/src/main/java/io/gravitee/rest/api/security/listener/AuthenticationSuccessListener.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/HttpClientServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/NewsletterServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java

fix: Allows to define an email on a first login with a inmemory user

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java

fix(management): import works with v1 definition

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/upgrade/IdentityProviderUpgrader.java

fix(oidc-idp): map emailRequired property from gravitee.yml file

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UsersResource.java

fix(portal): query must not be null

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/application/registration/ClientRegistrationServiceImpl.java

fix: Fail to save a Client registration config

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionResource.java

fix: manage my api-keys

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java

fix: Allows to override virtual host with entrypoints

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/RatingMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingAnswerResource.java

fix(portal): add link to the avatar for the author of api rating answer

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiSubscribersResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml

fix(portal): api subscribers can be filtered

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ViewServiceImpl.java

Closes gravitee-io/issues#3636

fix(view): Default ALL view must have a key

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java

fix(multi-env): count only accepted and paused subscription

---

gravitee-management-api-idp/gravitee-management-api-idp-core/pom.xml
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/CurrentUserResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/AbstractAuthenticationResource.java
gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java
gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
gravitee-management-api-security/pom.xml
gravitee-management-api-security/src/main/java/io/gravitee/management/security/SecurityConfiguration.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/cookies/CookieGenerator.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/csrf/CookieCsrfSignedTokenRepository.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/csrf/CsrfRequestMatcher.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/JWTAuthenticationFilter.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/UserServiceTest.java
pom.xml

Closes gravitee-io/issues#3634

fix: Add support for CSRF / upgrade nimbus + upgrade java-jwt

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPlansResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java

Closes gravitee-io/issues#3644

fix(api): improve filtering of api data

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/EmailValidator.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/PasswordValidator.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/PasswordFormatInvalidException.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/spring/ServiceConfiguration.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/validator/RegexPasswordValidator.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/UserServiceTest.java
gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#3656

fix(user): Check the email and password during registration

---

gravitee-management-api-service/pom.xml
gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/PageContentUnsafeException.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/sanitizer/AllowAllSanitizer.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/sanitizer/HtmlSanitizer.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_CreateTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_UpdateTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/sanitizer/AllowAllSanitizerTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/sanitizer/HtmlSanitizerTest.java
gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
pom.xml

Closes gravitee-io/issues#3637

feat(page): allow to optionally sanitize page content

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationsResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/application/ApplicationListItem.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java

fix(management): manage applications pictures in managementUI

---

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#3663

feat(csrf): allow to optionally enable csrf protection

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PortalConfigEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/parameters/Key.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/RecaptchaFilter.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/ReCaptchaService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/HttpClientServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ReCaptchaServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ConfigServiceTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ReCaptchaServiceImplTest.java
gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#3655

feat(captcha): add captcha protection if feature is enabled

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/transformer/UserDocumentTransformer.java

Closes gravitee-io/issues#3665

fix(user): Do not search on email domain

---

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/csrf/CookieCsrfSignedTokenRepository.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/CsrfIncludeFilter.java
gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#3662

feat(csrf): handle csrf cross-domain

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json

fix(portal): add metadata in subscriptions

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java

fix(portal): add metadata about API in subscription

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/param/AnalyticsParam.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml

feat: User dashboard

---

gravitee-management-api-security/src/main/java/io/gravitee/management/security/csrf/CookieCsrfSignedTokenRepository.java

Closes gravitee-io/issues#3662

fix(csrf): handle csrf cross-domain

---

gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/RecaptchaFilter.java

Closes gravitee-io/issues#3655

feat(captcha): add captcha on login

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/import-api.definition_enum_lowercase.json

Closes gravitee-io/issues#3402

fix(import): security value for plan data can be filled in lowercase

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/spring/ServiceConfiguration.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_EnumValueWittenLowercaseTest.java

Closes gravitee-io/issues#3406

refactor: export api with enum vales in lowercase

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/provider/UriBuilderRequestFilter.java
gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/provider/UriBuilderRequestFilterTest.java
pom.xml

Closes: gravitee-io/issues#3641

 X-Forwarded headers fix for ports

---

gravitee-management-api-security/src/main/java/io/gravitee/management/security/csrf/CookieCsrfSignedTokenRepository.java

Closes gravitee-io/issues#3673

fix(csrf): set http-only on csrf cookie

---

pom.xml

Closes gravitee-io/issues#3679

chore: Upgrade netty dependency

---

gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/csrf/CookieCsrfSignedTokenRepository.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/RecaptchaFilter.java

Closes gravitee-io/issues#3676

feat(captcha): allow cors 'X-Recaptcha-Token' header by default

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationLogsResource.java

feat: Allows to export logs

---

pom.xml

Closes gravitee-io/issues#3419

chore: Upgrade gravitee-node dependency

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/search/Indexable.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/application/registration/ClientRegistrationServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/SearchEngineServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/transformer/ApiDocumentTransformer.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/transformer/PageDocumentTransformer.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/transformer/UserDocumentTransformer.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_DeleteTest.java

Closes gravitee-io/issues#3689

Merge 1.25.25

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/UserServiceTest.java

fix(portal): add default envionment role when creating a user

---

gravitee-rest-api-idp/gravitee-rest-api-idp-api/src/main/java/io/gravitee/rest/api/idp/api/authentication/UserDetails.java
gravitee-rest-api-idp/gravitee-rest-api-idp-api/src/main/java/io/gravitee/rest/api/idp/api/identity/SearchableUser.java
gravitee-rest-api-idp/gravitee-rest-api-idp-core/src/main/java/io/gravitee/rest/api/idp/core/authentication/impl/CompositeIdentityManager.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UserEntity.java
gravitee-rest-api-model/src/test/java/io/gravitee/rest/api/model/UserEntityTest.java

fix(management): return a new display name for jdenticon (as in portal)

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ViewMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ViewMapperTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ViewServiceImpl.java

Fixes gravitee-io/issues#3477
Fixes gravitee-io/issues#3481

fix(portal): return View object instead of id in APIs

---

gravitee-rest-api-idp/gravitee-rest-api-idp-api/src/main/java/io/gravitee/rest/api/idp/api/authentication/UserDetails.java
gravitee-rest-api-idp/gravitee-rest-api-idp-api/src/main/java/io/gravitee/rest/api/idp/api/identity/SearchableUser.java
gravitee-rest-api-idp/gravitee-rest-api-idp-core/src/main/java/io/gravitee/rest/api/idp/core/authentication/impl/CompositeIdentityManager.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UserEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java

Fix(management): Display name is the same for portal and management

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java

fix(portal): homepage is not display when in a folder

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/UserMapperTest.java

fix(portal): fix unit test for displayName

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java

fix: Error on membership while deleting an application

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiMetricsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResourceTest.java

fix(portal): allows applications to be sorted

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResourceTest.java

fix(portal): fix case sensitive sort and add UT

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/UserResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/common/DefaultRoleEntityDefinition.java

fix(management): remove USER-READ permission on default USER role

---

gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/MembershipService_AddRoleToMemberOnReferenceTest.java

fix(management): fix unit test

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ThemeResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ThemesResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ThemeMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ThemeResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ThemeServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ThemeServiceTest.java

fix: The theme is not merged when it is never modified by the user

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ConfigurationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResourceTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/ApplicationGrantTypesNotAllowedException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/ApplicationGrantTypesNotFoundException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/ApplicationRedirectUrisNotFound.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/ApplicationResponseTypesNotFound.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/ApplicationTypeNotFoundException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/application/ApplicationTypeServiceImpl.java
gravitee-rest-api-service/src/main/resources/applications/types.json
gravitee-rest-api-service/src/main/resources/themes/default/definition.json
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationService_CreateTest.java

fix(portal): improve application resource

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/spring/RestManagementConfiguration.java
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
pom.xml

Closes gravitee-io/issues#3660

feat(el): sandbox EL to whitelisted methods

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java

fix: remove not found exception on PageService#search

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java

fix(portal): return null instead of Exception when no PrimaryOwnerFound

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java

fix(portal): assume that there is no orphan pages

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json

refactor: updgrade theme portal for gv-stepper ui-component

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ViewsResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/ViewEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ViewMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ViewsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ViewMapperTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ViewService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EnvironmentServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ViewServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/DefaultViewUpgrader.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/EnvironmentService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ViewService_FindTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ViewService_GetTotalApisByViewTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ViewService_UpdateTest.java

Closes gravitee-io/issues#3767

feat(management): remove Default view ALL and 'default' field

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/NewsletterServiceImpl.java

fix: Newsletter changes

---

gravitee-rest-api-service/src/main/resources/dashboards/application_geo.json

fix: Errors when selecting a filter on an empty user agent

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ThemeServiceTest.java
gravitee-rest-api-service/src/test/resources/themes/base-definition.json
gravitee-rest-api-service/src/test/resources/themes/custom-definition.json
gravitee-rest-api-service/src/test/resources/themes/legacy-definition.json

fix(portal): remove gv-info

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/AbstractResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/DashboardsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/quality/QualityRulesResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/ApiListItem.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/UnauthorizedAccessException.java

fix: some resource accesses should be restricted

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java

fix: resolve topApis resource

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AlertServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiSerializer.java
pom.xml

Cloess gravitee-io/issues#3754

feat(alert): Add support for alert commands

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/configuration/identity/github/GitHubIdentityProviderEntity.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java

fix(social): login with GitHub without an email attribute

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json

fix(portal): upgrade theme definition

---

gravitee-rest-api-standalone/gravitee-rest-api-standalone-container/src/main/java/io/gravitee/rest/api/standalone/jetty/JettyServerFactory.java

Closes gravitee-io/issues#3823

fix(http): Define correctly the SSL context for the server

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/AbstractResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/DashboardsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/quality/QualityRulesResource.java

fix: Default admin can't go to the dashboard and settings menu

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/SocialIdentityProviderEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/am/AMIdentityProviderEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/github/GitHubIdentityProviderEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/google/GoogleIdentityProviderEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/oidc/OIDCIdentityProviderEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/IdentityProviderMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/IdentityProviderMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/auth/OAuth2AuthenticationResourceTest.java
gravitee-rest-api-service/src/main/resources/themes/default/definition.json

fix(api): idp icons are managed by UIs

---

gravitee-management-api-standalone/gravitee-management-api-standalone-container/src/main/java/io/gravitee/management/standalone/jetty/JettyServerFactory.java

Closes gravitee-io/issues#3820

fix(http): Define the SSL for the HTTP server

---

pom.xml

fix(LinkedCaseInsensitiveMap): implement the missing methods

---

pom.xml

fix(cors): add regex support

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateWithDefinitionTest.java
pom.xml

fix: Timeout to display the gallery with a lot of APIs

---

pom.xml

Closes gravitee-io/issues#3888

fix(reporter): Upgrade dependency to gravitee-node

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java

Closes gravitee-io/issues#3393

fix(logs): Show the full URI path in logs and CSV export

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApplicationMapper.java

fix(portal): set hasClientId application's to false if clientId is empty

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ThemeServiceTest.java

refactor: remove gv-code from portal's theme

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java

fix: Export CSV is not working anymore on subscriptions

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/AbstractResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPlansResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiSubscribersResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CategoriesResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/DashboardsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformAnalyticsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformEventsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/portal/PortalApisResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/quality/QualityRulesResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApiService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_FindByUserTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/UserServiceTest.java

feat: Better handling of read access on API's items

---

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#3354

feat(elasticsearch): Add supprot for HTTP proxy

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AlertServiceImpl.java

Closes gravitee-io/issues#3942

feat(alert): Add API's primary owner in alert command

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/PlanMapper.java

fix(portal): Wrong type in list pour subscriptionQuery

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_FindByUserTest.java

fix(portal): do not search for private APIs if user is not authenticated

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/PlanMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/PlanMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceNotAuthenticatedTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java

fix: Subscribed attribute is not necessary on the list of plans

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/param/ApisParam.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceTest.java

fix(portal): new query param to select or not promoted apis

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AuditServiceImpl.java

fix: Error on application audit log

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/AbstractResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java
gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/ApiPagesResourceNotAdminTest.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/PermissionService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PermissionServiceImpl.java

fix(apis): rework manageable status for APIs

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java

fix(email): attach base64 images to email template

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApplicationMetadataEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewApiMetadataEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewApplicationMetadataEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewReferenceMetadataEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/ReferenceMetadataEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApiMetadataEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApplicationMetadataEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateReferenceMetadataEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/ApplicationPermission.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationMetadataResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationResource.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApplicationMetadataService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApplicationMetadataNotFoundException.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/MetadataNotFoundException.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AbstractReferenceMetadataService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiMetadataServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationMetadataServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AuditServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MetadataServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/upgrade/DefaultRolesUpgrader.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiMetadataServiceTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/MetadataServiceTest.java

feat: Application metadata

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/AlertEventRuleEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/alert/AlertTriggerEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/alert/NewAlertTriggerEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/alert/UpdateAlertTriggerEntity.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/PlatformAlertsResource.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/AlertService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/AlertTemplateInvalidException.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AlertServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_CreateWithDefinitionTest.java
pom.xml

Closes gravitee-io/issues#3970

feat(alert): Support for alert templates

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiListItem.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java

fix: Breaking change with virtual_hosts

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java

fix: Bad template used when a subscription is approved

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/command/CommandEntity.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/CommandService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/CommandServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/SearchEngineServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/transformer/ApiDocumentTransformer.java
gravitee-management-api-services/gravitee-management-api-services-search-indexer/src/main/java/io/gravitee/management/services/search/ScheduledSearchIndexerService.java

fix: Better handling of indexation of searchable data

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/SearchEngineServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/searcher/UserDocumentSearcher.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/transformer/UserDocumentTransformer.java

feat: Allows to search / register user on OIDC provider

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java

fix: Plan cannot be subscribed in some case

---

pom.xml

Closes gravitee-io/issues#4003

fix(el): fix el initialization

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml

fix(portal): change default portal API URL

---

pom.xml

Closes gravitee-io/issues#3105

feat(grpc): Add GRPC support

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AnalyticsServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java

Closes gravitee-io/issues#4044

fix(plan): Handle properly unknown plan

---

gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml

Depends on gravitee-io/issues#3935
Closes gravitee-io/issues#3933

feat(sandbox): sandbox Groovy shell

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java

fix: Sometimes social login is not working

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java

fix: Incorrect audit when deleting a portal page

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/sanitizer/HtmlSanitizer.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_UpdateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/sanitizer/HtmlSanitizerTest.java
pom.xml

fix(management): execute template rendering before sanitizing

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/EmailNotification.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/builder/EmailNotificationBuilder.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/TicketServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/TicketServiceTest.java

https://github.com/gravitee-io/issues/issues/4105

feat: use "Reply-To" instead of from when sending support email

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/PlanService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PlanServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/PlanService_DepreciateTest.java

fix(management): deprecate API even with staging plan

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/EventService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EventServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/InstanceServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/WorkflowServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/EventServiceTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/InstanceServiceTest.java
gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

fix(management): #4100 addition of a ttl for gateways in unknown state

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/swagger/parser/OAIParser.java

fix: When the property info is missing in a OAI file, there is no log

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/model/Subscription.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionsResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/SubscriptionsResource.java

Closes gravitee-io/issues#3965

feat(management): add more information about the application on subscription screen

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EmailServiceImpl.java

fix: Copy to sender not working anymore when creating a ticket

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java

fix(management): remove group from plans and pages when deleted

---

gravitee-rest-api-idp/gravitee-rest-api-idp-api/src/main/java/io/gravitee/rest/api/idp/api/authentication/UserDetails.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CurrentUserResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/CurrentUserResourceTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewExternalUserEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateUserEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UserEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/NewsletterService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/UserService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/NewsletterServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
pom.xml

feat: Allows user to subscribe to the newsletter after login

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiModelEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/GroupEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewGroupEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateGroupEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/UpdateApiEntity.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApplicationServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java
pom.xml

Closes gravitee-io/issues#4134

fix(management): do not notify when adding a user in a group, api or application

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionsResource.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java

doc: Fix documentation of listApplicationSubscriptions endpoint

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/SearchEngineServiceImpl.java

fix: Useless stacktrace when a document cannot be indexed

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/jackson/ser/api/ApiSerializer.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_EnumValueWittenLowercaseTest.java
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_20.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport-1_25.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExport.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportMultipleEndpointGroups-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithouGroup.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers-1_20.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers-1_25.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMembers.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMetadata-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMetadata-1_20.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMetadata-1_25.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutMetadata.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_20.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages-1_25.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPages.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans-1_15.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans-1_20.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans-1_25.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/export-convertAsJsonForExportWithoutPlans.json
pom.xml

fix: Add consistency on field properties in EL

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/DefaultParameterUpgrader.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/SubscriptionServiceTest.java
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#4144

feat(management): remove portalURL config from gravitee.yml

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PageRevisionEntity.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/PageRevisionRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/PageRevisionService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageRevisionServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageRevisionServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_DeleteTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_ImportDescriptorTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_ImportDirectoryTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_UpdateTest.java
pom.xml

feat(management-api/reporter): #146 addition of page revision

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ReferenceMetadataMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationMetadataResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ReferenceMetadataMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/AbstractResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationMetadataResourceTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MetadataServiceImpl.java

fix(portal): allow to manage Application's metadata from portal

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java

fix(management): check if ExcludedGroups exist for pages and plans

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java

fix(management): add API information if parsing exception

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/search/lucene/transformer/UserDocumentTransformer.java

fix(management): test if the email has @ before indexing it

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/GroupServiceImpl.java

fix(management): remove groupMapping when a group is deleted

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/AllowOriginNotAllowedException.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateTest.java

fix(management): apply patern validation on cors allow-origin field

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/CommandServiceImpl.java

Closes gravitee-io/issues#4214

fix(audit): Do not append IDs if they are already known

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/NewApiEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/UpdateApiEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/application/ApplicationListItem.java

Closes gravitee-io/issues#4232

fix(oai): Sets must be considered as array of objects

---

gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/notifications/portal/PORTAL.USER_CREATED.yml

fix(management): add PORTAL.USER_CREATED.yml template

---

gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_CreateAPITest.java

test(management): reactivate SwaggerService_CreateAPITest

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PortalConfigEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ConfigServiceTest.java

feat: Add settings for OpenAPI doc format

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java

Closes gravitee-io/issues#4252

fix(api): Do not validate cors origin if none configured

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AlertServiceImpl.java

fix:  Handle default values for notifiers configuration

---

gravitee-management-api-idp/gravitee-management-api-idp-api/src/main/java/io/gravitee/management/idp/api/authentication/UserDetails.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/CurrentUserResource.java
gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/CurrentUserResourceTest.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java

Closes gravitee-io/issues#4250

feat(account): allow user to delete his own account

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalPagesResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/CategoryEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewCategoryEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PageEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateCategoryEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/CategoryMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/CategoryMapperTest.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/CategoryRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/CategoryService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/CategoryServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_DeleteTest.java

Closes gravitee-io/issues#4067

feat(management): associate a page to a category

---

gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/PageRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/PageService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_AutoFetchTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_ImportAutFetchDescriptorMockFetcher.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_ImportSimplePageMockFetcher.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_MockAutoFetchDescriptorFetcherConfiguration.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_MockSinglePageFetcherConfiguration.java
gravitee-rest-api-services/gravitee-rest-api-services-auto-fetch/pom.xml
gravitee-rest-api-services/gravitee-rest-api-services-auto-fetch/src/main/assembly/plugin-assembly.xml
gravitee-rest-api-services/gravitee-rest-api-services-auto-fetch/src/main/java/io/gravitee/rest/api/services/fetcher/ScheduledAutoFetchService.java
gravitee-rest-api-services/gravitee-rest-api-services-auto-fetch/src/main/java/io/gravitee/rest/api/services/fetcher/spring/AutoFetchConfiguration.java
gravitee-rest-api-services/gravitee-rest-api-services-auto-fetch/src/main/resources/plugin.properties
gravitee-rest-api-services/pom.xml
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
pom.xml

feat(management): auto fetch pages based on user configuration

---

pom.xml

Closes gravitee-io/issues#4256

feat(proxy): allow use of system proxy in endpoint configuration

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionResource.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/ApiKeyService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/ApiKeyAlreadyActivatedException.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiKeyServiceTest.java
pom.xml

Closes gravitee-io/issues#4227

feat(apikey): allow apikey reactivation

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java

Closes gravitee-io/issues#4269

feat(management): replace DISABLED by REJECTED

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/RoleServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/RoleService_UpdateTest.java
pom.xml

Closes gravitee-io/issues#4258

fix(role): fix error when updating role using jdbc

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java

fix: Cannot save an API with health check inheritance

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java

fix: all user invitations are made for the idp 'gravitee'

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java

fix(management): fix slf4j template

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/TokenAuthenticationFilter.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/utils/AuthoritiesProvider.java
gravitee-management-api-security/src/test/java/io/gravitee/management/security/filter/TokenAuthenticationFilterTest.java

refactor OAuth2AuhtenticationResource to mutualize code wit TokenAuthentivationFilter
Addition of Tests for TokenAuthFilter
fix gravitee-io/issues#4289

issue: addition of Authorities when Personal Token is used

---

gravitee-rest-api-service/src/main/resources/themes/default/definition.json

Closes https://github.com/gravitee-io/gravitee-cockpit/issues/64

feat: update theme

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/CommandServiceImpl.java

fix: Do not add same acknowledgments for a node

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateUserEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateViewEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/UpdateApiEntity.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/CurrentUserResource.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/UserService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/UserServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ViewServiceImpl.java

Closes gravitee-io/issues#4268

feat(management): allow to delete a picture from API, View & user

---

gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/TokenAuthenticationFilter.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/MembershipServiceImpl.java

fix(management): set user authorities within userDetails object

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AlertServiceImpl.java
gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

fix: Subject prefix is not used

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AlertServiceImpl.java

fix: Expose API metadata in alert notification templates

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateApplicationEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateCategoryEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/UpdateApiEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/CategoryServiceImpl.java

From API, applications, categories and users
Closes gravitee-io/issues#4316

feat(picture): allow to delete pictures

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AlertServiceImpl.java

Closes gravitee-io/issues#4364

fix(alert): Provide the API id

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AlertServiceImpl.java

Closes gravitee-io/issues#4374

fix(alert): Template are always considered as enabled

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_Update_DefaultLoggingMaxDurationTest.java

Closes gravitee-io/issues#4377

fix(logging): Do not add useless parenthesis

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/AbstractResourceTest.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/SecurityConfiguration.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/filter/TokenAuthenticationFilter.java
gravitee-management-api-security/src/main/java/io/gravitee/management/security/utils/AuthoritiesProvider.java
gravitee-management-api-security/src/test/java/io/gravitee/management/security/filter/TokenAuthenticationFilterTest.java
gravitee-management-api-security/src/test/java/io/gravitee/management/security/utils/AuthoritiesProviderTest.java

Closes gravitee-io/issues#4352

fix(management): move AuthoritiesProvider to Spring managed bean

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/converter/api/OAIToAPIConverter.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/converter/api/SwaggerV2ToAPIConverter.java

Fixed for Swagger / and OpenAPI

4336  [management] Import of OpenAPI/Swagger containing path with parameters failed

---

docker/Dockerfile

Linked to https://github.com/gravitee-io/issues/issues/4375

update AdoptOpenJDK image to 11.0.8

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentConfigurationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentResource.java
gravitee-rest-api-management/gravitee-rest-api-management-security/src/main/java/io/gravitee/rest/api/management/security/config/BasicSecurityConfigurerAdapter.java

Closes gravitee-io/issues#4376

fix(management): avoid breaking changes. Deprecates resources instead

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PortalConfigEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/expectedPortalConfiguration.json
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/portalConfigEntity.json

Closes gravitee-io/issues#4370

refactor(settings): remove useless portal title setting

---

gravitee-rest-api-idp/gravitee-rest-api-idp-core/src/main/java/io/gravitee/rest/api/idp/core/plugin/IdentityProviderPluginHandler.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PoliciesResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PolicyResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/FetcherEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PolicyEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PolicyListItem.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/plugins/RepositoryPluginHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/FetcherService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/PluginService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/PolicyService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ResourceService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PluginNotFoundException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AbstractPluginService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/FetcherServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PolicyServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ResourceServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/plaftform/plugins/ServiceDiscoveryServiceImpl.java
pom.xml

Closes gravitee-io/issues#4123

feat(plugin): Add support for plugin icon and documentation

---

pom.xml

Linked to gravitee-io/issues#4123

build(): change gravitee-plugin version

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResourceTest.java

Closes gravitee-io/issues#4171

feat(subscription): add keys to subscription creation response

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/transformer/entrypoints/EntrypointsOAITransformer.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/transformer/page/PageConfigurationOAITransformer.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/SwaggerService_TransformTest.java

Closes gravitee-io/issues#4389

fix(swagger): use right url in swagger and redoc page

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/AbstractResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiResourceNotAdminTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApiService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java

fix(apis): improvide canReadAPI method

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java

fix(api): ensure backward compatibility for the updateWithDefinition resource

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/notifiers/impl/EmailNotifierServiceImpl.java

fix: Do not send emails to an unresolved expression

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/NewApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/UpdateApplicationEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/ApiListItem.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/NewApiEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/PathsSwaggerDef.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/api/UpdateApiEntity.java
gravitee-management-api-model/src/main/java/io/gravitee/management/model/application/ApplicationListItem.java

fix(management/swagger): provide right type for array items

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/AlertServiceImpl.java

fix: Alert's template must be considered as enabled

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/NotifierService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/NotifierServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/SubscriptionServiceTest.java

feat(mng): send email notification to api subscriber

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_UpdateTest.java
pom.xml

feat(management): addition of review actions in audit log

---

gravitee-rest-api-idp/gravitee-rest-api-idp-core/src/main/java/io/gravitee/rest/api/idp/core/authentication/impl/CompositeIdentityManager.java

fix: Error while searching through LDAP to transfer application

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PermissionServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PermissionServiceTest.java

fix(api): send management url only when user has appropriate roles

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/UserResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/UsersResource.java
gravitee-rest-api-management/gravitee-rest-api-management-security/src/main/java/io/gravitee/rest/api/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/ResetPasswordUserEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UsersResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java
gravitee-rest-api-security/src/main/java/io/gravitee/rest/api/security/filter/RecaptchaFilter.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/UserService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PasswordAlreadyResetException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/UserStateConflictException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PermissionServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_CreateWithDefinitionTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateWithDefinitionTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_Update_DefaultLoggingMaxDurationTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/FilteringServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/RatingServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/SubscriptionServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/TokenServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/UserServiceTest.java
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/templates/passwordReset.html
pom.xml

fix(portal): reset password improvement

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalPagesResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/portal/PortalApisResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/PortalPagesResourceAnonymousTest.java
gravitee-rest-api-management/gravitee-rest-api-management-security/src/main/java/io/gravitee/rest/api/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/filter/PermissionsFilter.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiInformationsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiMetricsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPageResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPagesResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiRatingsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/CategoriesResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/CategoryResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/PageResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/PagesResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/security/RequirePortalAuth.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java

fix(mng/portal): improve force login feat

---

gravitee-rest-api-service/src/main/resources/schema/xGraviteeIODefinition.json

fix: Error in description of jsonpath xGraviteeIODefinition.json

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/RoleUserResource.java

fix(management): remove only the selected role

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PortalConfigEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ConfigServiceTest.java

feat: label's dictionary

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java

Closes gravitee-io/issues#4411

feat(api): import swagger to update api using put method

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/VirtualHostService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/InvalidVirtualHostException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/VirtualHostServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/VirtualHostServiceTest.java

If domain restrictions exists on current environment, virtual hosts must respect them,
Closes gravitee-io/issues#4308

feat(virtual-host): implement domain restriction

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPageMediaResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPlansResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CategoryResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalPageMediaResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/UserResource.java

Closes gravitee-io/issues#4551

fix(management): Cannot update roles of a user anymore

---

pom.xml

fix(scheduled-service): we should not lost the polling configuration if we disable a service

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiKeysResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiSubscriptionResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiSubscriptionsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiKeysResourceTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiSubscriptionResourceTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiSubscriptionsResourceTest.java
gravitee-rest-api-model/pom.xml
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PortalConfigEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/ProcessSubscriptionEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/validator/CustomApiKey.java
gravitee-rest-api-model/src/test/java/io/gravitee/rest/api/validator/CustomApiKeyTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApiKeyService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/SubscriptionService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiKeyServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiKeyServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/SubscriptionServiceTest.java

feat: allows to define a custom api-key

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformTicketsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/param/TicketsParam.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/PlatformTicketsResourceTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/TicketEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/TicketQuery.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/common/Sortable.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/common/SortableImpl.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/TicketsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/param/TicketsParam.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/TicketsResourceTest.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/TicketRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/TicketNotFoundException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/TicketServiceTest.java

feat: support tickets history

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PortalConfigEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ParameterServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ConfigServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ParameterServiceTest.java
pom.xml

feat: override settings via envvars

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java

fix: Default admin can't see/go to the dashboard and settings menu

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java

fix: Tests failing while creating an unpublished page

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GroupMembersResource.java
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/templates/notifications/portal/PORTAL.GROUP_INVITATION.yml

Use the created membership to retrieve the user
Fixes gravitee-io/issues#4609

fix(management): get the user id from the right place

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/HttpClientServiceImpl.java

Closes gravitee-io/issues#4600

fix(http-client): Use a relative path to make the HTTP call

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/PageEntity.java
gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiPageResource.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/PageService.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/PageServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/swagger/parser/OAIParser.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/swagger/OAIDescriptor.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_CreateTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_ImportDescriptorTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/PageService_ImportDirectoryTest.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_ParseTest.java
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/swagger-v2-no-info-name.json
gravitee-management-api-service/src/test/resources/io/gravitee/management/service/swagger-v2-no-info-name.yaml

 fix(api): swagger descriptors with missing info are still displayed and imported but an error message is displayed on import

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MessageServiceImpl.java

fix(management): add message title in template param

---

docker/Dockerfile

Addresses https://github.com/gravitee-io/issues/issues/4511

Update AdoptOpenJDK Docker image to 11.0.9

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java

reset roles cache after adding a role
Fixes gravitee-io/issues#4619

fix(management): backport 4591

---

gravitee-rest-api-idp/gravitee-rest-api-idp-api/src/main/java/io/gravitee/rest/api/idp/api/identity/User.java
gravitee-rest-api-idp/gravitee-rest-api-idp-memory/src/main/java/io/gravitee/rest/api/idp/memory/lookup/InMemoryIdentityLookup.java
gravitee-rest-api-idp/gravitee-rest-api-idp-memory/src/main/java/io/gravitee/rest/api/idp/memory/lookup/InMemoryUser.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/providers/User.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/IdentityServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java

fix(api): update roles on first login for users previously automatically created when adding memeberships

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformEventsResource.java

fix(dashboard): test if API is deleted

---

.gitignore
Makefile
README.adoc
docker/Dockerfile-dev
docker/compose/docker-compose-dev.yml
postman/.gitignore
postman/README.adoc
postman/env/Gravitee.io-Demo-Environment.json
postman/env/Gravitee.io-Localhost-Environment.json
postman/env/Gravitee.io-Nightly-Environment.json
postman/scripts/tests.sh
postman/test/Gravitee.io-Issues.postman_collection.json
postman/test/Gravitee.io-Test.Suite-Create.And.Start.Api.postman_collection.json
postman/test/Gravitee.io-Test.Suite-Create.Application.postman_collection.json
postman/test/graviteeio-apim-portal-authorizations-collection.json
postman/test/graviteeio-apim-portal-errors-collection.json
postman/test/graviteeio-apim-portal-subscription-collection.json

Fixes https://github.com/gravitee-io/issues/issues/4587

feat: integration tests improvements

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java

fix(management): add null test

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PlanService_FindByApiTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PlanService_FindByIdTest.java

fix(management): load flows plan from api definition for v2 api

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_UpdateTest.java

Fixes https://github.com/gravitee-io/issues/issues/4655

fix: impossible to move documentation page to folder

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/ApiDocumentSearcher.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/PageDocumentSearcher.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/ApiDocumentTransformer.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/PageDocumentTransformer.java

fix: Cannot search on labels with some special characters

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CategoryResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CurrentUserResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CustomUserFieldsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalResource.java

apply additional adjustments for gravitee-io/issues#4394 
resolves https://github.com/gravitee-io/issues/issues/4533

Improve generation of swagger definition

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_UpdateTest.java

fix(management): resolve page reorder

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/DefaultParameterUpgrader.java

fix(management): remove null constraint violation at startup

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/param/LogsParam.java

… page
Closes gravitee-io/isues#4666

chore(): Prepare next version

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PageEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PlanEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PlanGeneralConditionRevisionException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/SubscriptionServiceTest.java

fix(management): check the version of GCU

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/MediaEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewPageEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/PageMapper.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MediaServiceImpl.java

fix(management): Manage attached resources in API import/export

---

gravitee-management-api-model/src/main/java/io/gravitee/management/model/configuration/dictionary/DictionaryTriggerEntity.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/event/DictionaryEvent.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/configuration/dictionary/DictionaryServiceImpl.java
gravitee-management-api-services/gravitee-management-api-services-dictionary/src/main/java/io/gravitee/management/services/dictionary/DictionaryRefresher.java
gravitee-management-api-services/gravitee-management-api-services-dictionary/src/main/java/io/gravitee/management/services/dictionary/DictionaryService.java
gravitee-management-api-services/gravitee-management-api-services-dictionary/src/main/java/io/gravitee/management/services/dictionary/provider/http/HttpProvider.java
gravitee-management-api-services/gravitee-management-api-services-sync/src/main/java/io/gravitee/management/services/sync/DictionaryManager.java
gravitee-management-api-services/gravitee-management-api-services-sync/src/main/java/io/gravitee/management/services/sync/SyncManager.java
gravitee-management-api-services/gravitee-management-api-services-sync/src/main/java/io/gravitee/management/services/sync/spring/SyncConfiguration.java
gravitee-management-api-services/gravitee-management-api-services-sync/src/test/java/io/gravitee/management/services/sync/DictionaryManagerTest.java

Closes gravitee-io/issues#4535

fix(dictionary): better handle dynamic dictionary configuration updates

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PortalConfigEntity.java

Closes gravitee-io/issues#4682

fix(settings): Ensure backward compatibility with previous existing properties from constants.json

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java

Closes gravitee-io/issues#4707

fix(api): Associate an ID to the api definition created from a swagger file

---

gravitee-rest-api-service/src/main/resources/flow/apim-schema.json
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/FlowServiceTest.java

fix(management): remove useless flow description

---

gravitee-rest-api-idp/gravitee-rest-api-idp-ldap/pom.xml
gravitee-rest-api-idp/gravitee-rest-api-idp-ldap/src/main/assembly/distribution.xml
gravitee-rest-api-idp/gravitee-rest-api-idp-repository/pom.xml
gravitee-rest-api-idp/pom.xml
gravitee-rest-api-standalone/gravitee-rest-api-standalone-container/pom.xml
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/gravitee-rest-api-standalone-distribution-zip/src/main/assembly/distribution.xml
pom.xml

Closes gravitee-io/issues#4565

chore: Manage and remove useless dependencies

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java

fix(management): use the right email template

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/EntrypointServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/EntrypointServiceTest.java

fix(management): allow multiple entrypoints on tag

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/MembershipService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java

resolves https://github.com/gravitee-io/issues/issues/4762

Bugfix: Environment Role is not being set with Role Mapping

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentsResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApplicationService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/EnvironmentService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/MembershipService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EnvironmentServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/VirtualHostServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/DefaultEnvironmentUpgrader.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/UserServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/VirtualHostServiceTest.java

Closes gravitee-io/issues#4151

feat(management): retrieve env by user

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/MembershipService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java

Closes https://github.com/gravitee-io/issues/issues/4780

resolves #4762 Environment Role is not being set with Role Mapping

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CurrentUserResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UserResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/UserServiceTest.java

feat(management): edit my account information

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/AbstractCommonConfigEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/PortalConfigEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/consoleConfigEntity.json
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/portalConfigEntity.json
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ConfigServiceTest.java

+ move analytics.client.timeout in portal config only
Closes gravitee-io/issues#4811

fix(settings): allow settings for ENVIRONMENT

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/builder/EmailNotificationBuilder.java

Closes gravitee-io/issues#4809

feat(email-template): change the subject of emails

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/TicketServiceTest.java

Closes gravitee-io/issues#4808

fix(support): use the right key regarding the context

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/filtering/FilteringService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/filtering/FilteringServiceImpl.java

when mixing filter and category, apply first filter and then category
Fixes gravitee-io/issues#4825

fix(portal): change the way APIs are filtered

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/filtering/FilteringService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/filtering/FilteringServiceImpl.java

Fixes https://github.com/gravitee-io/issues/issues/4826

fix: backport 4825

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/EnvironmentsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/MediaResource.java

Fixes https://github.com/gravitee-io/issues/issues/4670

fix: backport 4669 to 3.0.x

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java

Fixes https://github.com/gravitee-io/issues/issues/4681

fix: backport 4680

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Analytics.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Api.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/ApiQualityMetrics.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/ApiReview.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Application.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Company.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Documentation.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/OpenAPIDocViewer.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Plan.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Portal.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/PortalConfigEntity.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ConfigService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/application/ApplicationTypeServiceImpl.java

- No need to be authenticated to use this resource
- Sensitive date are not returned (CORS & EMAIL)
Fixes gravitee-io/issues#4830

fix(console): need a /portal resource for console runtime

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/migration/APIV1toAPIV2Converter.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/migration/APIV1toAPIV2ConverterTest.java
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/service/migration/api-withOnlyPaths-migrated.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/service/migration/api-withOnlyPlans-migrated.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/service/migration/api-withPathsAndPlans-migrated.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/service/migration/api-withPathsAndPlans.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/service/migration/plans.json

Fixes https://github.com/gravitee-io/issues/issues/4829

feat: improve API conversion from v1 definition to v2 definition

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UserResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/UserMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/UserResourceTest.java

Fixes https://github.com/gravitee-io/issues/issues/4675

fix: User without rights on Applications should not see the menu

---

gravitee-rest-api-fetcher/src/main/java/io/gravitee/rest/api/fetcher/impl/FetcherConfigurationFactoryImpl.java
gravitee-rest-api-fetcher/src/test/java/io/gravitee/rest/api/fetcher/FetcherConfigurationFactoryTest.java

Closes gravitee-io/issues#4806

fix(fetcher): Allow to import from fetcher with unknown fetcher configuration properties

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-rest-api-service/pom.xml
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/builder/JerseyClientBuilder.java
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#4398

fix(proxy): support proxy settings on OAuth2AuthenticationResource

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java

fix(management): fix swagger documentation description

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalResource.java

fix(management/swagger spec): fix response entity for getPortalConfig

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_ExportAsJsonTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_ExportAsJsonTestSetup.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_ExportAsJsonV2Test.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_gRPC_ExportAsJsonTestSetup.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_gRPC_ExportAsJsonV2Test.java

using API environmentId when fetching parameters
Fixes gravitee-io/issues#4862

fix(console): fix /tasks resource

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PolicyServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/converter/api/OAIToAPIConverter.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/converter/api/OAIToAPIV2Converter.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/migration/APIV1toAPIV2Converter.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/validator/PolicyHelper.java

fix(management): resolve import of wsdl with rest to soap option

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EmailServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/spring/EmailConfiguration.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/spring/GraviteeJavaMailManager.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/spring/GraviteeJavaMailManagerTest.java

Closes gravitee-io/issues#4904

fix(mail): fix error with authenticated smtp

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/DashboardsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentAnalyticsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/param/AnalyticsParam.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/EnvironmentAnalyticsResourceTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/DashboardReferenceType.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/DashboardServiceImpl.java
gravitee-rest-api-standalone/gravitee-rest-api-standalone-container/pom.xml
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/gravitee-rest-api-standalone-distribution-zip/src/main/assembly/distribution.xml
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/assembly/distribution.xml
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/dashboards/home.json
pom.xml

Fixes https://github.com/gravitee-io/issues/issues/4747

feat: console dashboard page

---

gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiAlertsResource.java

fix(management): use api permissions instead of env one for alert

---

gravitee-management-api-service/src/main/java/io/gravitee/management/service/exceptions/SubscriptionNotActiveException.java
gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java
gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiKeyServiceTest.java

Closes gravitee-io/issues#4889

fix(subscription): Do not allow to reactivate an apikey for a closed plan

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiResourceTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/ApiDeploymentEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApiService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-services/gravitee-rest-api-services-dynamic-properties/src/main/java/io/gravitee/rest/api/services/dynamicproperties/DynamicPropertyUpdater.java

Fixes https://github.com/gravitee-io/issues/issues/4742

feat: associate a label to an api deployment

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/OrganizationResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/EnvironmentEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/OrganizationEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateEnvironmentEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateOrganizationEntity.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/OrganizationRepositoryProxy.java
gravitee-rest-api-service/pom.xml
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/EnvironmentService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/OrganizationService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EnvironmentServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/OrganizationServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/RoleServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/EnvironmentCommandHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/MembershipCommandHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/OrganizationCommandHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/UserCommandHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/DefaultEnvironmentUpgrader.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/DefaultOrganizationUpgrader.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/EnvironmentService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/OrganizationService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/EnvironmentCommandHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/MembershipCommandHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/OrganizationCommandHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/UserCommandHandlerTest.java
gravitee-rest-api-standalone/gravitee-rest-api-standalone-container/pom.xml
pom.xml

Closes gravitee-io/issues#4287

feat(cockpit): handle organization and environment commands

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GraviteeManagementApplication.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/AbstractAuthenticationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/CockpitAuthenticationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/spring/RestManagementConfiguration.java
gravitee-rest-api-management/gravitee-rest-api-management-security/src/main/java/io/gravitee/rest/api/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateOrganizationEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/common/JWTHelper.java

Need to review gravitee-io/issues#4287 first
Closes gravitee-io/issues#4522

feat(cockpit): add cockpit authentication support

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/identity/IdentityProviderServiceImpl.java

Fixes https://github.com/gravitee-io/issues/issues/4956

fix: social idp are not enabled after creation

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/common/GraviteeContext.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java

Fixes https://github.com/gravitee-io/issues/issues/4937

fix: social authentication is not working anymore

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_CreateWithDefinitionTest.java

Fixes https://github.com/gravitee-io/issues/issues/4944

fix: duplicate pages when importing an API

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/migration/APIV1toAPIV2Converter.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/migration/APIV1toAPIV2ConverterTest.java
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/service/migration/api-withOnlyPlans-migrated.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/service/migration/api-withPathsAndPlans-migrated.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/service/migration/plans.json

fix(management): add missing fields when migrating plans

---

gravitee-rest-api-spec-converter/src/main/java/io/gravitee/rest/api/spec/converter/wsdl/WSDLToOpenAPIConverter.java

fix(management): manage WSDL imports when creating/updating an API with WSDL

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java

fix(management): Allow to update policies when importing a swagger

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/ApiListItem.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApiService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/quality/ApiQualityMetricHealthcheck.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiQualityMetricHealthcheckTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_hasHealthCheckEnabledTest.java

Closes gravitee-io/issues#4750

feat(management): add health-check information in apis

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java
gravitee-rest-api-services/gravitee-rest-api-services-dynamic-properties/src/main/java/io/gravitee/rest/api/services/dynamicproperties/CronHandler.java
gravitee-rest-api-services/gravitee-rest-api-services-dynamic-properties/src/main/java/io/gravitee/rest/api/services/dynamicproperties/DynamicPropertiesService.java
pom.xml

feat(management): be able to enable/disable health-check during some periods

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/InstallationCommandHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/MembershipCommandHandler.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/InstallationCommandHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/MembershipCommandHandlerTest.java

Add an `InstallationCommandHandler`
Closes gravitee-io/issues#4945

feat(cockpit): propagate installation status to installation

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java

https://github.com/gravitee-io/issues/issues/4796

fix(management): use CORS allow origin regex from RFC6454

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationService_FindByUserTest.java

🛑🚧 Do not merge, this branch is based on https://github.com/gravitee-io/issues/issues/4945. PRs related to these issue must be merged first ! 🚧
Fixes https://github.com/gravitee-io/issues/issues/4777

feat: handle environment switching

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApplicationService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationService_FindAllTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/UserServiceTest.java

Fixes https://github.com/gravitee-io/issues/issues/4776

feat: default application creation

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/CockpitAuthenticationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-security/src/main/java/io/gravitee/rest/api/management/security/config/BasicSecurityConfigurerAdapter.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/EnvironmentPermissionsEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/EnvironmentService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EnvironmentServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/EnvironmentService_FindByUserAndIdOrHridTest.java

Fixes https://github.com/gravitee-io/issues/issues/4778

feat: display current env id in console url

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/CockpitAuthenticationResource.java
gravitee-rest-api-security/src/main/java/io/gravitee/rest/api/security/utils/AuthoritiesProvider.java

fix: set the security context in the cockpit authentication

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/RoleMappingEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/UserService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/configuration/identity/IdentityProviderService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/identity/IdentityProviderServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/IdentityProviderUpgrader.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/UserServiceTest.java

* handle backward compatibility, as the previous format in DB is ENVIRONMENT:ROLE_NAME and the new is ENVIRONMENT:ENV_ID:ROLE_NAME
* shared code between OAuth2AuthenticationResource and UserServiceImpl
* add a unit test in UserService
Closes gravitee-io/issues#4803

feat(management): allow to configure roleMapping on several environments

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GraviteeManagementApplication.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/installation/InstallationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/OrganizationResource.java

Closes https://github.com/gravitee-io/issues/issues/5037

fix: move installation resource under organization

---

gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExport-1_20.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExport-1_25.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExport-3_0.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExport.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMembers-1_20.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMembers-1_25.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMembers-3_0.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMembers.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMetadata-1_20.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMetadata-1_25.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMetadata-3_0.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutMetadata.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPages-1_20.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPages-1_25.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPages-3_0.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPages.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPlans-1_20.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPlans-1_25.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPlans-3_0.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsJsonForExportWithoutPlans.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-gRPC-convertAsJsonForExport-1_20.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-gRPC-convertAsJsonForExport-1_25.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-gRPC-convertAsJsonForExport-3_0.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-gRPC-convertAsJsonForExport-3_0V2.json
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-gRPC-convertAsJsonForExport.json

test: fix unit tests for api import-export

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/UserCommandHandler.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/UserCommandHandlerTest.java

fix(management): set the "picture" field when creating a user from cockpit

---

gravitee-rest-api-services/gravitee-rest-api-services-dictionary/src/main/java/io/gravitee/rest/api/services/dictionary/provider/http/HttpProvider.java
gravitee-rest-api-services/gravitee-rest-api-services-dictionary/src/main/java/io/gravitee/rest/api/services/dictionary/provider/http/configuration/HttpProviderConfiguration.java
gravitee-rest-api-services/gravitee-rest-api-services-dictionary/src/test/java/io/gravitee/rest/api/services/dictionary/provider/http/HttpProviderTest.java
gravitee-rest-api-services/gravitee-rest-api-services-dictionary/src/test/resources/mappings/request03.json
gravitee-rest-api-services/gravitee-rest-api-services-dynamic-properties/src/main/java/io/gravitee/rest/api/services/dynamicproperties/provider/http/HttpProvider.java
gravitee-rest-api-services/gravitee-rest-api-services-dynamic-properties/src/test/resources/mappings/request03.json

Fixes https://github.com/gravitee-io/issues/issues/4746

feat: define HTTP verb for dynamic properties and dictionaries

---

gravitee-rest-api-services/gravitee-rest-api-services-sync/src/main/java/io/gravitee/rest/api/services/sync/SyncManager.java

**Issue**
Fix https://github.com/gravitee-io/issues/issues/5040

fix: make SyncManager handles API of different organizations

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/annotations/ParameterKey.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Email.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java

fix(settings): Do not expose sensitive information

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java

fix(apis): admin must has access to all apis

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentsResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_ExportAsJsonTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_ExportAsJsonTestSetup.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_FindByIdTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_gRPC_ExportAsJsonTestSetup.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationService_FindByIdTest.java

Fixes https://github.com/gravitee-io/issues/issues/5038

fix: apis and applications should not be accessible from another environment

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java

Closes gravitee-io/issues#5088

fix: Cannot get tasks in case of pending subscriptions

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiSubscriptionResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationSubscriptionsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiSubscriptionResourceTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApplicationSubscriptionsResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/UserService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java

fix(subscriptions): handle unknown users when fetching for subscriptions

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java

A user can manage an API if it has at least a create, update or delete permission on this API.
Fixes gravitee-io/issues#5096

fix: show only manageable apis

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApiService.java

fix(api): handle response templates when saving a plan

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PolicyServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PolicyServiceTest.java

fix(policy): handle default values during policy configuration validation

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPageResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPagesResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiPagesResourceAdminTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PageType.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPagesResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/PagesResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPagesResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ConfigurationResourceTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/PagesResourceTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PageMarkdownTemplateActionException.java

feat: global markdown template pages

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiMetadataResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiMetadataResourceTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApiService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AbstractReferenceMetadataService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiMetadataServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationMetadataServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserMetadataServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/SearchEngineServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/ApiDocumentSearcher.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/ApiDocumentTransformer.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/SearchIndexUpgrader.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiMetadataServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_CreateWithDefinitionTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateWithDefinitionTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_Update_DefaultLoggingMaxDurationTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/ApiDocumentTransformerTest.java

https://github.com/gravitee-io/issues/issues/5017

feat: be able to search apis by metadata

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/migration/APIV1toAPIV2Converter.java
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/service/migration/plans.json

Fixes https://github.com/gravitee-io/issues/issues/5122

fix: closed plans should not be visible on design studio

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java

Closes gravitee-io/issues#5162

feat(management): prevent po group to be added to an API

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PageUsedByCategoryException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_UpdateTest.java

Fixes https://github.com/gravitee-io/issues/issues/5114

fix: Permissions issue when accessing category documentation

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GroupMembersResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/MembershipService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/UserService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/MembershipService_GetMembersTest.java

fix: add pagination for members in group page

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPlansResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiPlansResourceTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PlanService_DeleteTest.java

Fixes https://github.com/gravitee-io/issues/issues/5113

fix: cannot delete a deprecated api anymore

---

gravitee-rest-api-gatling/pom.xml

chore(): update version of gatling module

---

pom.xml

Fixes https://github.com/gravitee-io/issues/issues/4715

feat: allows to define a prefix for collections / tables

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/UserCommandHandler.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/UserCommandHandlerTest.java

fix(cockpit): allow the user command handler to update an existing user

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/CockpitAuthenticationResource.java

feat: allow to change current organization in the console

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/UserMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ApplicationMapperTest.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/MemberMapperTest.java

fix(portal): provide USER permission in addition of APPLICATION ones

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/MembershipRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/MembershipService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/MembershipService_FindUserMembershipTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/UserServiceTest.java
pom.xml

fix(management-api): mutualize OAuthResource for portal and console

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiAlertsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationAlertsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformAlertsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/param/AlertAnalyticsParam.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/AlertAnalyticsQuery.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/alert/AlertAnalyticsEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/AlertAnalyticsService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/AlertService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AlertAnalyticsServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AlertServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/AlertAnalyticsServiceTest.java

feat: dashboard of all alerts

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationResource.java

fix(applications): set groups when updating an application

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformTicketsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/UsersResource.java

Closes gravitee-io/issues#5289

fix: responseContainer Annotation does not work for Page and PagedResult

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/NewIdentityProviderEntity.java

Closes gravitee-io/issues#5297

fix: Some fix on idp creation

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/CurrentUserResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/NewsletterResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/NewsletterService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/NewsletterServiceImpl.java

Closes gravitee-io/issues#5269

feat: Dynamic newsletter taglines

---

Makefile
README.adoc
postman/bulk/categories.json
postman/bulk/gio_apis.json
postman/bulk/gio_applications.json
postman/bulk/gio_configuration.json
postman/scripts/bulk.sh

chore: improve makefile to add bulk of data

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/model/TokenEntity.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/AbstractAuthenticationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/auth/AbstractAuthenticationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/auth/OAuth2AuthenticationResource.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml

fix(oauth): add id_token and access_token

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MessageServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/MessageService_GetRecipientIdsTest.java

feat(management): contact subscribers as an api publisher

---

pom.xml

fix(health-check): handle null 'schedule' field on disabled health check

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java

fix(user): assign pre-registered user to expected oidc provider

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewPageEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java

fix(management): handle no visibility when creating a page

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/MembershipCommandHandler.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/MembershipCommandHandlerTest.java

fix(cockpit): make MembershipCommandHandler idempotent

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PageEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UserEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/ApiEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/search/Indexable.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/OrganizationRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/OrganizationService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/OrganizationServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/RoleServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/DocumentSearcher.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/DocumentTransformer.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/ApiDocumentSearcher.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/PageDocumentSearcher.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/UserDocumentSearcher.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/ApiDocumentTransformer.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/PageDocumentTransformer.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/UserDocumentTransformer.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/SearchIndexUpgrader.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_AutoFetchTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_DeleteTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_FindByIdTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_ImportDescriptorTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_ImportDirectoryTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_UpdateTest.java
pom.xml

fix(search): support apis and users search in multi env and org context

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/GoodbyeCommandHandler.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/GoodbyeCommandHandlerTest.java
pom.xml

Closes gravitee-io/issues#5170

feat(cockpit): Manage installation deletion

---

gravitee-rest-api-idp/gravitee-rest-api-idp-api/src/main/java/io/gravitee/rest/api/idp/api/authentication/UserDetails.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/CurrentUserResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java

Closes gravitee-io/issues#4870

feat: Display groups in user account information

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Portal.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ParameterServiceImpl.java

Closes gravitee-io/issues#4856

feat: Override the main sentence in the homepage

---

gravitee-rest-api-standalone/gravitee-rest-api-standalone-container/pom.xml
pom.xml

Closes gravitee-io/issues#4898

feat(cache): Use the new caching abstraction layer

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EmailServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java

Fixes https://github.com/gravitee-io/issues/issues/5352

fix: addressException when trying to submit a ticket with custom from

---

gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/NodeMonitoringRepositoryProxy.java
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/pom.xml
pom.xml

Closes gravitee-io/issues#5104

feat(cockpit): Propagate monitoring data to cockpit

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApplicationResourceAdminTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApplicationResourceNotAdminTest.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApplicationsResourceTest.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/ApplicationRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApplicationService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/SubscriptionService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/ApplicationActiveException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/SubscriptionNotClosedException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationService_FindByNameTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationService_RestoreTest.java
pom.xml

Fixes https://github.com/gravitee-io/issues/issues/4453

feat: allow to restore an archived application

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPageResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/TemplateProcessingException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MessageServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MetadataServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/NotificationTemplateServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/notification/NotificationTemplateService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/notifiers/impl/EmailNotifierServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/EmailNotifierServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/MetadataServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_CreateTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_UpdateTest.java

Fixes https://github.com/gravitee-io/issues/issues/5192

fix: documentation pages not displayed

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApplicationsResourceNotAdminTest.java

Fixes https://github.com/gravitee-io/issues/issues/5427

fix: fix archives application sorting and permissions issue

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/CurrentUserResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/GroupServiceImpl.java

add path /groups for current user
fix gravitee-io/issues#5416

fix(management): resolve api creation & permissions

---

postman/test/gio_apis.json

Hasbeen run three times on nightly env and no problem for me

test: fix postman tests on clean up phase for searching APIs

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java

fix(login): get default environment for social/oidc login

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/UsersResource.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#5450

fix: add a portal whitelist for user registration and reset password

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java

Closes gravitee-io/issues#5413

fix: a membership for member : USER and ref : GROUP already exists.

---

gravitee-rest-api-idp/gravitee-rest-api-idp-api/src/main/java/io/gravitee/rest/api/idp/api/authentication/UserDetails.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/CurrentUserResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java

fix gravitee-io/issues#5416
fix gravitee-io/issues#5421

backport 5416

---

gravitee-rest-api-security/pom.xml
pom.xml

Closes gravitee-io/issues#5471

fix: APIM dependencies upgrade

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewPlanEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_CreateWithDefinitionTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateWithDefinitionTest.java

fix(management): preserve plan id when importing an api

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/EventEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/InstanceEntity.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/DictionaryRepositoryProxy.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/EnvironmentRepositoryProxy.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/OrganizationRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EventServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/InstanceServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/dictionary/DictionaryServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/EventServiceTest.java

Fixes https://github.com/gravitee-io/issues/issues/5357

feat: allow to associate a gateway to environments

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
pom.xml

Closes gravitee-io/issues#5298

feat(management): allow to filter by context-path

---

gravitee-rest-api-management/gravitee-rest-api-management-security/src/main/java/io/gravitee/rest/api/management/security/config/BasicSecurityConfigurerAdapter.java

fix(management): make /portal protected

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/sanitizer/UrlSanitizerUtils.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/sanitizer/UrlSanitizerUtilsTest.java

Fixes https://github.com/gravitee-io/issues/issues/5450

fix: check uri syntax for user registration and reset password

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationsResource.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/ApplicationRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApplicationService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationService_FindByNameTest.java

Fixes https://github.com/gravitee-io/issues/issues/5518

fix: search only user authorized applications by name

---

pom.xml

Closes gravitee-io/issues#5545

chore: upgrade to latest version

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java

When performing a patch update on a page to modify its publication state, the request does not define a visibility. In that case, we must keep the existing visibility status of the page and apply it to the related pages (translations and links)
Fixes gravitee-io/issues#5569

fix(management): check visibility on patch update

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java

fix(plans): correctly map plan selection rule for V2 APIs

---

docker/Dockerfile-dev
docker/compose/docker-compose-dev.yml
gravitee-rest-api-management/gravitee-rest-api-management-rest/pom.xml
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/pom.xml
gravitee-rest-api-security/pom.xml
pom.xml

Backport gravitee-io/issues#5533
Closes gravitee-io/issues#5552

fix: Error when updating user's avatar

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/sanitizer/UrlSanitizerUtils.java

fix(url): check confirmlUrl is not null before sanitize it

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/configuration/identity/IdentityProviderResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/IdentityProvidersResourceTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/GroupMappingEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/RoleMappingEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/configuration/identity/UpdateIdentityProviderEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/UserServiceTest.java

Closes gravitee-io/issues#5561

fix: not default role when user created with external IDP

---

gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/AlertTriggerRepositoryProxy.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/ApplicationRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java

Related to https://github.com/gravitee-io/gravitee-repository/pull/206

Update repository proxies to match updated interfaces

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java

Merge tag '3.8.3'

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/UpdateApiEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/flow/FlowServiceImpl.java

**Issue**
https://github.com/gravitee-io/issues/issues/5642
Fix issues related to json properties deserialization.

fix: use specific json deserializer for 'properties'

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationAlertServiceImpl.java

Fixes https://github.com/gravitee-io/issues/issues/5341

fix(portal): fix null exception if no group for an application

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/UpdateApiEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java

Closes gravitee-io/issues#5303

fix: Unable to use default image on API

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/QualityRuleServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/QualityRuleServiceTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/5626
Unable to update a quality rule with a jdbc repository
fix gravitee-io/issues#5626

fix: unable to update a quality rule

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java

fix(management): keep flows plan when reimport

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/5611
a valid regex has to be accepted in the allowed origin

fix(cors): allow all valid regex

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SwaggerServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/converter/api/OAIToAPIConverter.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/converter/api/OAIToAPIV2Converter.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/SwaggerService_CreateAPITest.java

fix(management): resolve policies on path creation / update

---

pom.xml

Closes gravitee-io/issues#2680

chore: Upgrade gravitee-cmmon dependency

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationAlertServiceImpl.java

Fixes https://github.com/gravitee-io/issues/issues/5657

fix: consumer alert without notification

---

pom.xml

Closes gravitee-io/issues#2680

chore: Upgrade gravitee-commoon dependency

---

gravitee-rest-api-service/src/main/resources/flow/configuration-schema-form.json

**Issue**
https://github.com/gravitee-io/issues/issues/4475
Change the font case of the flow Mode  enumeration. Linked to the gravitee-definition modification.

fix: change font case for enumeration

---

gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/pom.xml

**Issue**
https://github.com/gravitee-io/issues/issues/3887
Add subscription-pre-expiration-notif service in standalone distribution.

feat: add subscription-pre-expiration-notif service in standalone distribution

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml

fix(management): clean CORS env vars & migration guide

---

gravitee-rest-api-idp/gravitee-rest-api-idp-ldap/src/main/java/io/gravitee/rest/api/idp/ldap/authentication/UserDetailsContextPropertiesMapper.java
gravitee-rest-api-idp/gravitee-rest-api-idp-ldap/src/test/java/io/gravitee/rest/api/idp/ldap/authentication/UserDetailsContextPropertiesMapperTest.java

Fixes https://github.com/gravitee-io/issues/issues/5619

fix(management): allow to specify multiple roles to map with ldap idp

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/CategoryServiceImpl.java

Fixes https://github.com/gravitee-io/issues/issues/5632

fix(management): categories order not set at creation

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/CockpitCommandServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandFactory.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/operation/ListEnvironmentOperationHandler.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/CockpitCommandServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandFactoryTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/bridge/operation/ListEnvironmentOperationHandlerTest.java
pom.xml

**Issue**
Related to https://github.com/gravitee-io/issues/issues/5526 but also fix `master` build
Currently, they were some issue because we were using services that haven't been injected properly yet. Also, update the gravitee-plugin version to be able to inject `CockpitConnector`.

Update injection mechanism in some CockpitCommand related services

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/CategoryServiceImpl.java

Fixes https://github.com/gravitee-io/issues/issues/5697

fix(management): backport 5632 categories order not set at creation

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/filter/MaintenanceFilter.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/ConsoleSettingsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ConsoleSettingsResourceTest.java

Fixes gravitee-io/issues#5731
**Issue**
https://github.com/gravitee-io/issues/issues/5731

fix: allow to disable maintenance mode

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java

Closes gravitee-io/issues#5724

fix: Subscription approval link not correct

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/filter/MaintenanceFilter.java

fix: factorize parameterService call to avoid performance issue

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionEntityStatus.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionRequestEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionTargetEntity.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/PromotionRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandFactory.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/services/CockpitService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/services/CockpitServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/promotion/PromotionService.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandFactoryTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/services/CockpitServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/promotion/PromotionServiceTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/5526
Create resource and service to send a Promotion request to another APIM instance.

Handle API Promotion request

---

gravitee-rest-api-fetcher/pom.xml
gravitee-rest-api-idp/gravitee-rest-api-idp-api/pom.xml
gravitee-rest-api-management/gravitee-rest-api-management-rest/pom.xml
gravitee-rest-api-model/pom.xml
gravitee-rest-api-services/gravitee-rest-api-services-dictionary/pom.xml
gravitee-rest-api-services/gravitee-rest-api-services-dynamic-properties/pom.xml
gravitee-rest-api-standalone/gravitee-rest-api-standalone-container/pom.xml
pom.xml

**Issue**
https://github.com/gravitee-io/issues/issues/5726
Bump jackson, json-smart, spring-integration versions

chore: bump jackson, json-smart, spring-integration versions

---

pom.xml

**Issue**
https://github.com/gravitee-io/issues/issues/5673
Add API_REVIEW_xxx event types to the list fo event types

fix(audit): add api-review events in audit event list

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/EnvironmentEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/OrganizationEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateEnvironmentEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateOrganizationEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/OrganizationService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/EnvironmentCommandHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/OrganizationCommandHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/producer/HelloCommandProducer.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EnvironmentServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/OrganizationServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/CockpitIdUpgrader.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/EnvironmentCommandHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/OrganizationCommandHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/producer/HelloCommandProducerTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/5781
The goal of introducing these cockpit ids is to ease the management of DEFAULT env/org when working with BridgeCommand

Handle `cockpitId` in Environment and Organization

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java

**Issue**
https://github.com/gravitee-io/issues/issues/5757
Do not remove existing roles if a role mapping is removed after a first connection.
**Additional context**
Backport of https://github.com/gravitee-io/issues/issues/5756

fix: roles initialized to default after removing a role mapping configuration

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionEntityAuthor.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionQuery.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionRequestEntity.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/PromotionRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/operation/ListEnvironmentOperationHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/operation/PromoteApiOperationHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/services/CockpitServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TaskServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/promotion/PromotionService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/promotion/PromotionTasksService.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/TaskServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandFactoryTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/bridge/operation/ListEnvironmentOperationHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/bridge/operation/PromoteApiOperationHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/services/CockpitServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImplTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/promotion/PromotionServiceTest.java
pom.xml

**Issue**
https://github.com/gravitee-io/issues/issues/5527
Handle API promotion requests and expose them as Tasks

Handle API promotion requests and expose them as Tasks

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionServiceImpl.java

**Issue**
https://github.com/gravitee-io/issues/issues/5781
Generate Promotion id in Service layer.

Generate Promotion id in Service layer

---

pom.xml

CICD operation : restoring state after 3.5.17 APIM release

restoring state right after release 3.5.17

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PromotionResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PromotionsResource.java
gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/OrganizationResource.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionQuery.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/EnvironmentRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/EnvironmentService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandFactory.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/operation/BridgeOperation.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/operation/ProcessPromotionOperationHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/services/CockpitService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/services/CockpitServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PromotionNotFoundException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EnvironmentServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/jackson/ser/api/ApiDefaultSerializer.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/promotion/PromotionService.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/VirtualHostServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/bridge/operation/ProcessPromotionOperationHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/services/CockpitServiceTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImplTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/promotion/PromotionServiceTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/5528

Accept or reject a promotion request

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/promotion/PromotionServiceTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/5531
Add a PROMOTION_CREATED audit event when a user is requesting an API Promotion

Add PROMOTION_CREATED audit event

---

gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GroupMembersResource.java

Issue https://github.com/gravitee-io/issues/issues/5614

fix: align getGroupMembers documentation

---

pom.xml

fix: manage '/' contextpath for Virtualhost

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewPlanEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java

fix(management): preserve order when import plan

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewPlanEntity.java
gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdatePlanEntity.java
gravitee-rest-api-model/src/test/java/io/gravitee/rest/api/model/NewPlanEntityTest.java
gravitee-rest-api-model/src/test/java/io/gravitee/rest/api/model/UpdatePlanEntityTest.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/PlanService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiDuplicatorService_CreateWithDefinitionTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiDuplicatorService_UpdateWithDefinitionTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PlanService_CreateOrUpdateTest.java

gravitee-io/issues#5842
Clone plans when doing an API promotion

feat: clone plans when doing an API promotion

---

gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/themes/definition.json

Related to https://github.com/gravitee-io/gravitee-ui-components/issues/284

fix: gv-select default background should be white

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/PlanService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_CreateOrUpdatePagesTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PlanService_DuplicatePlansTest.java

**Issue**
NA
Fix issue with pages and plans when duplicating an API multiple times

Fix issue with pages and plans when duplicating an API multiple times

---

pom.xml

feat(resource-cache): update api-cache-provider version

---

gravitee-rest-api-standalone/gravitee-rest-api-standalone-container/pom.xml

**Issue**
https://github.com/gravitee-io/issues/issues/5656

Update `standalone-container` pom.xml to fix missing yml files issue

---

gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdatePlanEntity.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/PlanService.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PlanInvalidException.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateWithDefinitionTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PlanService_UpdateTest.java

fixes gravitee-io/issues#5694
fixes gravitee-io/issues#5820

fix: preserve flows on plan during API Import

---

gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapper.java
gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml

fix: addition of create_at attribute to Api definition

---

gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/EventRepositoryProxy.java
gravitee-rest-api-repository/src/main/java/io/gravitee/rest/api/repository/proxy/PlanRepositoryProxy.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/SearchIndexUpgrader.java
gravitee-rest-api-services/gravitee-rest-api-services-sync/src/main/java/io/gravitee/rest/api/services/sync/SyncManager.java

**Issue**
https://github.com/gravitee-io/issues/issues/5615
Implements new repository methods needed to optimize gateway sync process.

feat(optim): add search latest events and search plan by api ids

---

gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml

**Issue**
gravitee-io/issues#3661
update gravitee.yml default configuration for mongo database

feat: upgrade mongo-driver

---

gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml

**Issue**
gravitee-io/issues#3661
Fixing the doc

doc: fix 'timeout' typo

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/GoodbyeCommandHandler.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionServiceImpl.java
gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/GoodbyeCommandHandlerTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImplTest.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/promotion/PromotionServiceTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/5746
https://github.com/gravitee-io/issues/issues/5527
- Reject all promotions to validate when installation is deleted from Cockpit
- Handle API creation and update permissions separately in API Promotion tasks

Improve API promotion

---

gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_CreateWithDefinitionTest.java
gravitee-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/import-new-api.definition+plans.json

fix(management): check plan policy configuration
