- pom.xml
This closes gravitee-io/issues#116
> Fix spring-webmvc version mismatch between gravitee (spring 4.2.6) and spring-security-oauth2 (4.0.9)

- gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java
Only the primary_owner of the API or an administrator is able to change the API's context-path to preserve coherency.
Closes gravitee-io/issues#203
> feat(api): Do not change context-path if user is not allowed to do so.

- gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiResource.java
permission is not returned when an api is deployed
> fix(deploy): deploy an api must return complete api definition

- gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
> fix(view): Update API views when removing a view

- gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java
> fix(oauth2): Use the value of picture property instead of the key itself

- gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
> feat(healthcheck): Update default HTTP port from 8093 to 18083

- gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java
- gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyExpired.html
> fix(mail): wrong mail subject + typo when apikey expire

- gravitee-management-api-idp/gravitee-management-api-idp-memory/src/main/java/io/gravitee/management/idp/memory/authentication/spring/InMemoryAuthenticationProviderConfiguration.java
- gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
fix(management-api): Allow for customization of password encoding/hashing algorithm for the InMemory IDP
Closes gravitee-io/issues#804
> fix(management-api): Allow for customization of password encoding/hashing algorithm for the InMemory IDP

- gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java
- gravitee-management-api-service/src/main/java/io/gravitee/management/service/RatingService.java
- gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/RatingServiceImpl.java
> fix(apis): api lists are slow to display

- gravitee-management-api-service/src/main/java/io/gravitee/management/service/notification/ApiHook.java
> fix(notifications): API key is written in 3 ways

- gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApisResource.java
This closes gravitee-io/issues#1142
> fix: API logos are not displayed correctly over HTTPS on apis list

- gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
It should be documented that the search-bases in ldap should be relative
> Documentation relative search-bases

- gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ConfigServiceImpl.java
This closes gravitee-io/issues#1293
> fix: The portal is not accessible when the documentation URL is empty

- gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationMembersResource.java
> fix(api, app): keep old permissions when switch to a new app/api

- gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
This closes gravitee-io/gravitee-alert-engine#22
> fix: Unable to connect cluster remotely

- gravitee-management-api-service/pom.xml
- gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SwaggerServiceImpl.java
- gravitee-management-api-service/src/test/java/io/gravitee/management/service/SwaggerService_TransformTest.java
- gravitee-management-api-service/src/test/resources/io/gravitee/management/service/openapi.json
- gravitee-management-api-service/src/test/resources/io/gravitee/management/service/openapi.yaml
- pom.xml
Changes:
- I am not sure about why swagger-parser was on a snapshot version here but in order to test this PR I had to set a released version of swagger-parser (2.0.9)
- I changed io.swagger.util.Json and io.swagger.util.Yaml imports to io.swagger.v3.core.util.Json and io.swagger.v3.core.util.Yaml respectively
- The readWithInfo method is ambiguous when used with null value as second parameter, so I had to cast the null parameter to make it work (probably due to swagger-parser update)
- I added a test case in order to check the fixed issue
Fixes https://github.com/gravitee-io/issues/issues/2014
> fix openapi security scheme type formatting

- gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
This closes gravitee-io/issues#2023
> fix: Error on duplicate endpoint names when creating via API

- gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/spring/EmailConfiguration.java
Closes gravitee-io/issues#2232
> fix(mail): Escape the content of the HTML templates when used for emails

- gravitee-management-api-model/src/main/java/io/gravitee/management/model/subscription/SubscriptionQuery.java
- gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApiSubscriptionsResource.java
- gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/ApplicationSubscriptionsResource.java
- gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/SubscriptionServiceImpl.java
> feat: Allows to search subscriptions by api key

- gravitee-management-api-model/src/main/java/io/gravitee/management/model/ApiKeyEntity.java
- gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiKeyServiceImpl.java
- gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiKeyServiceTest.java
> fix: Renew Subscription also renews expired API keys (not revoked)

- gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
- gravitee-management-api-service/src/test/java/io/gravitee/management/service/ApiService_DeleteTest.java
> fix: When deleting an API, alerts should be also deleted

- gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/apiKeyExpired.html
closes #875 
fix gravitee-io/issues#3208
> fix: Missing informations on email template for expired api-key

- gravitee-management-api-rest/pom.xml
- gravitee-management-api-services/gravitee-management-api-services-dictionary/pom.xml
- gravitee-management-api-services/gravitee-management-api-services-dynamic-properties/pom.xml
- pom.xml
spring 5.1.3 -> 5.2.5
spring-security 5.1.5 -> 5.2.5
jersey 2.29 -> 2.30.1
jetty 9.4.20 -> 9.4.28
freemarker 2.3.28 -> 2.3.30
guava 20.0 -> 29.0-jre
json-path 2.3.0 -> 2.4.0
snakeyaml 1.18 -> 1.26
jackson 2.9.8 -> 2.10.3
json-schema-validator 2.2.8 -> 2.2.13
swagger-jersey-jaxrs 1.5.23 -> 1.6.1
jersey-spring4 -> jersey-spring5
java-jwt 2.2.1 -> 3.10.2
Closes gravitee-io/issues#3652
> chore(dependencies): upgrade dependencies

- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceTest.java
> fix(portal): order top APIs with specific order and not by name

- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/expectedPortalConfiguration.json
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/portalConfigEntity.json
- gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java
- gravitee-rest-api-security/src/main/java/io/gravitee/rest/api/security/filter/RecaptchaFilter.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ReCaptchaServiceImpl.java
- gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
Enable CRSF by default.
Enable default password policy following owasp requirements.
Enable pages html sanitizer.
Closes gravitee-io/issues#3668
> feat(security): add recaptcha and csrf support on portal

- gravitee-rest-api-service/pom.xml
> fix: Node cannot start on an empty database in some context

- gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/ApiServiceImpl.java
Closes gravitee-io/issues#4338
> fix(api): Ensure that a final unpublish event is send when an API is deleted

- gravitee-rest-api-service/pom.xml
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SwaggerServiceImpl.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/converter/api/OAIToAPIConverter.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/SwaggerService_CreateAPITest.java
* fixes pages creation when no pageId defined
* do not fail when non existing tags are imported. Filter them instead
* exclude old version of json-patch to prevent conflicts
Fixes gravitee-io/issues#4439
> fix(management): fix for API import

- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/CategoriesResource.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/CategoriesResourceNotAuthenticatedTest.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/CategoriesResourceTest.java
> fix(api): do not send categories with no APIs available for user

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/HttpClientServiceImpl.java
> fix: Cannot create an API from a Gravitee.io definition anymore

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/common/DefaultRoleEntityDefinition.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java
* Retrieve all reviewers of an API, to send them a notification mail when a review is requested.
* Add a missing permission on default REVIEWER role.
Closes gravitee-io/issues#4436
> feat(management): send a notification email when API in review

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ThemeServiceImpl.java
- gravitee-rest-api-standalone/gravitee-rest-api-standalone-container/pom.xml
- gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/gravitee-rest-api-standalone-distribution-zip/src/main/assembly/distribution.xml
- gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/assembly/distribution.xml
* use java 8 methods
* include `themes` folder in the distribution
Fixes gravitee-io/issues#4617
> fix(management): build modification

- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java
> fix: Example cURL not displayed for an unpublished API on subscriptions

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java
Closes gravitee-io/issues#4704
> Do not store duplicated labels for an API

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/SubscriptionNotActiveException.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiKeyServiceImpl.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiKeyServiceTest.java
> fix(management): an apikey should not be reactivated on closed plans

- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
> fix(portal): don't allow a user to click on an unpublished API detail

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
> fix(management): revoke all apikey when closing a subscription

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/parser/OAIParser.java
Sometimes, the parser generates a null error messages.
Fixes gravitee-io/issues#4967
> fix(management): don't care about null error message

- docker/Dockerfile
Updates to newer AdoptOpenJDK base image. Linked to https://github.com/gravitee-io/issues/issues/4964
> Update AdoptOpenJDK image

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/commands/HelloCommandProducer.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/commands/HelloCommandProducerTest.java
- gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
**Issue**
Closes https://github.com/gravitee-io/issues/issues/4981
Add `API_URL` and `UI_URL` in the `additionalInformation` sent to cockpit in the HelloCommand.
The default values are the ones to make everything work locally.
> feat: add API and UI URLs in HelloCommandSend to Cockpit

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/sanitizer/HtmlSanitizer.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/sanitizer/HtmlSanitizerTest.java
Closes gravitee-io/issues#5031
> fix(page): Do not allow injection in Markdown links

- gravitee-rest-api-services/gravitee-rest-api-services-dynamic-properties/src/main/java/io/gravitee/rest/api/services/dynamicproperties/CronHandler.java
**Issue**
Fix https://github.com/gravitee-io/issues/issues/5041
Previously, the scheduled handler can never be cancelled as the wrong `timerId` was updated.
> fix: update the correct timer id in CronHandler to be able to stop it

- gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GroupMembersResource.java
- gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/GroupEntity.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/GroupService.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/GroupServiceImpl.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/GroupService_UpdateTest.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/MembershipService_AddRoleToMemberOnReferenceTest.java
- pom.xml
* add restriction to prevent defining PRIMARY_OWNER as default role in a group
* authorize at most 1 API PRIMARY OWNER member in a group
* add a boolean 'hasAPIPrimaryOwner' in the GroupEntity. It is computed only if needed.
Closes gravitee-io/issues#5133
> feat(management): Manage API PO in a group

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApplicationService_CreateTest.java
use the environmentId parameter of the create method instead of `GraviteeContext.getCurrentEnvironment()`
Fixes gravitee-io/issues#5144
> fix(management): fix the default application creation

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/builder/JerseyClientBuilder.java
Closes gravitee-io/issues#5281
> fix: Do not use system proxy by default for OAuth authentication

- gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java
When looking for APIs to subscribe from an application, we need to list the same APIs as if the user were on portal. To do this, we can use the query param 'portal' (which is only use for that case) to determine which APIs should be returned.
The application owner will be able to see only the published APIs that are public or of which he is a member.
Fixes gravitee-io/issues#5223
> fix(management): use 'portal' query param

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/CategoryServiceImpl.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/DefaultCategoryUpgrader.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/CategoryService_CreateTest.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/CategoryService_UpdateTest.java
* modify the CategoryUpgrader to add a creation date
* add a creation date when creating a category
* add an update date when updating a category
* modify the way the hash for the picture is computed (use now the creation date if the update date is null)
Fixes gravitee-io/issues#5275
> fix(management): update dates of a category

- gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/PageEntity.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
- postman/test/gio_apis.json
- postman/test/gio_documentation.json
> fix(management): keep compatibility with excluded_groups in pages

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
When looking for reviewers of the API, so they can be sent an email when a review is asked, we were looking into the groups of the API but without checking if this API had groups. So a NullPointerException happened when an API did not have any group.
Fixes gravitee-io/issues#5568
> fix(api-review): check API has groups to avoid NPE

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/sanitizer/UrlSanitizerUtils.java
Note: this PR has been opened on master to allow merge of 3.8.2 tag. The same fix must be backported on 3.5.x (and upper).
Closes gravitee-io/issues#5567
> fix(url): check confirmlUrl is not null before sanitize it

- gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/subscription/SubscriptionQuery.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
- gravitee-rest-api-services/gravitee-rest-api-services-subscriptions/src/main/java/io/gravitee/rest/api/services/subscriptions/ScheduledSubscriptionsService.java
- gravitee-rest-api-services/gravitee-rest-api-services-subscriptions/src/test/java/io/gravitee/rest/api/services/subscriptions/ScheduledSubscriptionsServiceTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/3887
- Use `endingAt` field to query Subscriptions needing to be closed
> Use `endingAt` field to query Subscriptions needing to be closed

- gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/model/OrganizationFlowConfiguration.java
- gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/FlowsResource.java
**Issue**
https://github.com/gravitee-io/issues/issues/4460
Add a resource to know if the platform has policies or not. This will be used in APIM console to inform a user, in API design, that some policies have been configured at the platform level.
> feat: add a resource to know if the platform has policies or not

- gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/ApiKeyEntity.java
- gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/SubscriptionEntity.java
- gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/key/ApiKeyQuery.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApiKeyService.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/SubscriptionService.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/builder/EmailNotificationBuilder.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiKeyServiceImpl.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/notification/ActionHook.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/notification/NotificationParamsBuilder.java
- gravitee-rest-api-services/gravitee-rest-api-services-subscription-pre-expiration-notif/pom.xml
- gravitee-rest-api-services/gravitee-rest-api-services-subscription-pre-expiration-notif/src/main/assembly/plugin-assembly.xml
- gravitee-rest-api-services/gravitee-rest-api-services-subscription-pre-expiration-notif/src/main/java/io/gravitee/rest/api/services/subscriptionpreexpirationnotif/ScheduledSubscriptionPreExpirationNotificationService.java
- gravitee-rest-api-services/gravitee-rest-api-services-subscription-pre-expiration-notif/src/main/java/io/gravitee/rest/api/services/subscriptionpreexpirationnotif/spring/SubscriptionPreExpirationNotificationConfiguration.java
- gravitee-rest-api-services/gravitee-rest-api-services-subscription-pre-expiration-notif/src/main/resources/plugin.properties
- gravitee-rest-api-services/gravitee-rest-api-services-subscription-pre-expiration-notif/src/test/java/io/gravitee/rest/api/services/subscriptionpreexpirationnotif/ScheduledSubscriptionPreExpirationNotificationServiceTest.java
- gravitee-rest-api-services/pom.xml
- gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
- gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/templates/subscriptionPreExpirationNotification.html
- pom.xml
**Issue**
https://github.com/gravitee-io/issues/issues/3887
Add pre-expiration notification for subscriptions:
- Add a scheduled service running every hour, it computes the subscription matching the expiration criteria and sends an email 
- Add a custom template for this email notification
- 
**Additional context**
In progress
> Add pre-expiration notification for subscriptions

- gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
- gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiResourceTest.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApiService.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/ApiService_UpdateTest.java
fixes gravitee-io/issues#5718
**Issue**
https://github.com/gravitee-io/issues/issues/5718
In this PR we want to prevent the update of plan into the API definition to avoid inconsistency between the UI and the information deploy into the gateway.
**Additional context**
> fix: test plan status before accepting updates

- gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/pom.xml
fixes gravitee-io/issues#5699
**Issue**
https://github.com/gravitee-io/issues/issues/5699
AutoFetch workes but the plugin isn't included into the APIM bundle
> fix: add auto-fetch plugin into distribution bundle

- pom.xml
**Issue**
https://github.com/gravitee-io/issues/issues/5764
Upgrade gravitee-node dependency in order to get a proper status on management health endpoint during startup phase.
> fix(probe): set probe status to "noReady" when starting

- gravitee-rest-api-service/pom.xml
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/sanitizer/UrlSanitizerUtilsTest.java
- pom.xml
**Issue**
https://github.com/gravitee-io/issues/issues/5822
Sometimes `RandomStringUtils` generate characters that make the URL invalid. This implies that sometimes, the `checkAllowed_invalidUrl` method fails with an UrlForbiddenException instead of InvalidDataException.
This commit replaces `RandomStringUtils` with `RandomStringGenerator` that allows to generate safe characters.
> fix: replace string generator for unit test

- gravitee-rest-api-repository/pom.xml
- gravitee-rest-api-service/pom.xml
- pom.xml
> chore: use new APIM monorepo as dependency

- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
- gravitee-rest-api-repository/pom.xml
- gravitee-rest-api-service/pom.xml
- pom.xml
> chore: use new APIM monorepo as dependency - 3.9.x

- gravitee-rest-api-repository/pom.xml
- gravitee-rest-api-service/pom.xml
- pom.xml
> chore: use new APIM monorepo as dependency - 3.8.x

- gravitee-rest-api-repository/pom.xml
- gravitee-rest-api-service/pom.xml
- pom.xml
> chore: use new APIM monorepo as dependency - 3.0.x

- gravitee-rest-api-repository/pom.xml
- gravitee-rest-api-service/pom.xml
- pom.xml
> chore: use new APIM monorepo as dependency - 3.5.x

- pom.xml
> chore: update gravitee-api-management dependency

- pom.xml
> chore: update gravitee-api-management dependency - 3.0.x

- pom.xml
> chore: update gravitee-api-management dependency - 3.5.x

- pom.xml
> chore: update gravitee-api-management dependency - 3.8.x

- pom.xml
> chore: update gravitee-api-management dependency - 3.9.x

- gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PromotionsResource.java
- gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/promotion/PromotionQuery.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PromotionAlreadyInProgressException.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionServiceImpl.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImpl.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImplTest.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/promotion/PromotionServiceTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/5746
- Handle multiple statuses in PromotionQuery
- Add endpoint to search API promotions
- Prevent users from being able to select an env already targeted by a CREATED or TO_BE_VALIDATED promotion
> Manage in progress promotion

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionServiceImpl.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/promotion/PromotionServiceTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/5746
Check only promotion targeting the same env before blocking a promotion request
> Fix check done when requesting a promotion 

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandFactory.java
**Issue**
NA
An environment can be linked to both an APIM and AM installation on Cockpit.
So to be able to send a command to the correct app cockpit need to know if it's targeting APIM or AM.
To avoid any issue we need to set a target scope for all BridgeCommand.
> Add scopes in all BridgeCommand's targets

- gravitee-rest-api-management/gravitee-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/security/config/GraviteeCorsConfigurationTest.java
- gravitee-rest-api-management/gravitee-rest-api-management-security/src/main/java/io/gravitee/rest/api/management/security/config/GraviteeCorsConfiguration.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/security/config/GraviteeCorsConfigurationTest.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/GraviteeCorsConfiguration.java
**Issue**
https://github.com/gravitee-io/issues/issues/5606
CORS configuration has changed since we updated Spring Security version. We should now use `setAllowedOriginPatterns` instead of `setAllowedOrigins`
> fix: update cors settings

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/HttpClientServiceImpl.java
Issue https://github.com/gravitee-io/issues/issues/5881
Impossible to import API from URL due to bug on HttpServiceImpl after update to Vert.x 4
**What has been done**
- Use request's path in `requestOptions.setURI` (which is a relative URI)
- Handle null parameters for
- headers
- body
Try to import an API by URL using https://api.gravitee.io/api-echo.json
> fix(management): fix HttpClientServiceImpl after update to vertx 4

- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/promotion/PromotionServiceImpl.java
**Issue**
NA
- put back checks on default group when creating an API, partially revert 540dbfc
- set promotion status to ERROR when the sending to cockpit fails
> Small fix and enhancement on API Promotion

- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPageResource.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPagesResource.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPageResourceNotAuthenticatedTest.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPageResourceTest.java
- gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPagesResourceTest.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/AccessControlService.java
- gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AccessControlServiceImpl.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/AccessControlServiceTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/5789
Use API roles instead of environment roles to check the access of API pages (if access control is defined on this API)
> fix: check API roles for API pages access control

- gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewPlanEntity.java
- gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdatePlanEntity.java
- gravitee-rest-api-model/src/test/java/io/gravitee/rest/api/model/NewPlanEntityTest.java
- gravitee-rest-api-model/src/test/java/io/gravitee/rest/api/model/UpdatePlanEntityTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/5881
Keep default value when creating a `NewPlanEntity` or a `UpdatePlanEntity` from a `PlanEntity`
> Keep default value when building a NewPlanEntity/UpdatePlanEntity

- gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/ImportPageEntity.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_ImportDescriptorTest.java
- gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/PageService_ImportDirectoryTest.java
**Issue**
gravitee-io/issues#5932
Remove the @NotNull annotation on the `Visibility` field of the `ImportPageEntity` class. Set visibility to PUBLIC by default.
> fix(documentation): set imported pages visible by default

- pom.xml
**Issue**
NA
gravitee-cockpit-connectors@2.0.0 needs gravitee-cockpit-api@1.7.0 & gravitee-plugin@1.18.0
> Bump `gravitee-plugin` & `gravitee-cockpit-api`

- pom.xml
**Issue**
https://github.com/gravitee-io/issues/issues/5890
Upgrade alert-api
> chore(alert): bump alert-api to 1.7.1
